### ISSUE TITLE
Feature request: Options for structure of summary file

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#1]
I think that in general, it does make sense to have samples be rows in the summary file, but it would be cool to be able to pass an option to `summarize` that would provide control over which axis samples go on vs. metrics. The default could also be to always the collection with more elements go on the row axis (i.e., when `|samples| > |metrics|`, samples are rows while `|metrics| > |samples|` could trigger samples to be columns and metrics to be rows)

**Comment by nsheff** [comment]
I haven't run into a use case where I'd want this... are you still interested in this?

**Comment by vreuter** [comment]
It still seems valid for a project with far fewer samples than metrics summarized (i.e., currently much more wide than tall), but that seems relatively infrequent, so I'm all good w/ this being closed if you want

**Comment by nsheff** [comment]
I'll close this as being not enough of a priority; if this comes up as an actual use case we can implement it.
