### ISSUE TITLE
Multi-package messaging

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#10]
Right now, with setting up the main application logger with `"looper"` as the name, we get information from `looper` but not `pep`, and vice-versa. It'd be nice to have from both.

**Comment by nsheff** [comment]
yeah, it should give both...

**Comment by nsheff** [comment]
Should have put this here: 

But now looper outputs this as its first line:

```
None as logs destination appears to be neither a filepath nor a stream.
```

which doesn't really make sense...how can we suppress that? is it coming from peppy?

**Comment by nsheff** [comment]
thanks, that solved it.

**Comment by vreuter** [comment]
OK cool, good eye on catching that
