### ISSUE TITLE
logging in html format

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#103]
caravel wants to output results of looper in HTML format... see: https://github.com/pepkit/caravel/issues/61

to do this, do we need to modify the `setup_looper_logger` function to accept a different formatter?

**Comment by nsheff** [comment]
@vreuter, @michalstolarczyk   can this issue be closed? I think this was solved by logmuse?

**Comment by vreuter** [comment]
A custom format is accepted; I'm not sure if/where one's being passed currently, though.
