### ISSUE TITLE
Python major version deprecation of escape sequences

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#105]
Here's a message seen during test suite execution on Python 3.5 but not Python 2.7:
```
looper/html_reports.py:222
  /home/vpr9v/code/looper/looper/html_reports.py:222: DeprecationWarning: invalid escape sequence \B
    """

looper/html_reports.py:1214
  /home/vpr9v/code/looper/looper/html_reports.py:1214: DeprecationWarning: invalid escape sequence \s
    m['key'] = m['key'].str.replace('^\s+', '')
```

**Comment by nsheff** [comment]
perhaps need to change to `[:space:]` or something

**Comment by nsheff** [comment]
@michalstolarczyk is this solved by the move to jinja templates?

**Comment by michalstolarczyk** [comment]
using `pytest` with `Python 3.6.5` I wasn't able to reproduce this.

but the line from the warning is still there

**Comment by michalstolarczyk** [comment]
I'll take care of that though

**Comment by michalstolarczyk** [comment]
closing, the `replace` method is not used anymore
