### ISSUE TITLE
Project organization

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#110]
Before a lot of additional parser-specific code is in `master` (https://github.com/pepkit/looper/pull/109), can we go ahead and make a `parser` subpackage? From discussion yesterday with @nsheff emerged the realization that, as was once the case, there are sort 2 somewhat cohesive functional subunits developing in this project.

Previously, there were the abstractions that represent components of a project, and a command-line tool for interaction with submitting/ed jobs, which now constitute `peppy` and `looper`, respectively. Now there's still the "command-line tool" notion--something like an _execution engine_--and a growing collection of types and functions to handle parsing user options (for `caravel` and for `looper` itself).

I think it'd be nice if we can (semi-)proactively organize the codebase in accordance with that distinction. Doing so is nice not only for conceptual and namespace modularity, but also to lessen the potential lift of ultimately actually packaging them separately.

**Comment by nsheff** [comment]
so -- `looper` is the command-line tool component;

can you name the other component? `parser` doesn't seem good to me.

**Comment by vreuter** [comment]
Ah yeah my bad...I shouldn't have dipped into those backticks on "parser"! Agree, that's a bad name, both overly generic and prone to collision. :thinking: what about `prjcli`...no easy pronunciation, but short, meaningful, and unlikely to collide?

**Comment by nsheff** [comment]
to me `looper` is the cli. 

`looper-processor`

so `looper` and `caravel` would both import the `looper-processor` submodule.

**Comment by vreuter** [comment]
Hmm, to me those actually sound flipped...I think of `looper` as the engine that powers user actions on a project. It seems like we're _separating_ the `cli` layer from that engine.
The natural dependency structure that you propose with the imports feels suggestive of the naming. 

We have three entities:
- The implementation of the ways in which to interact with a `Project` (i.e., the `Executor`s) and the bridge between a `Project` and a pipeline (`PipelineInterface`)
- Definitions and parsing of the parameters for each kind of user/`Project` interaction
- `caravel`

With the first and last importing the middle, the second one feels like the "interface," with a name like "processor" (to me, at least) mapping more closely to the functionality by the first item listed above.

**Comment by nsheff** [comment]
I'm having trouble following your argument... is there any way you can say it while referring to entities with names, and directly? where does the cli fit into this? I can't parse your first and second bullets.

**Comment by vreuter** [comment]
Discussion with @nsheff reveals a different dependency/import structure than I'd been aware of, so we think it makes sense to _not_ yet do any separate subpackaging here. In the future, the prime candidate for separation and spin-off is `PipelineInterface`, especially in light of plans to add capabilities to it.
