### ISSUE TITLE
PyPI?

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#111]
I just realized...we don't have this on PyPI? Do we want to? As expected, `looper` is taken, though it has just one release (5 years old), so we may be able to get the name? @nsheff

**Comment by nsheff** [comment]
https://github.com/pypa/pypi-legacy/issues/789

**Comment by vreuter** [comment]
Ha OK I'll also follow that thread.

**Comment by nsheff** [comment]
https://pypi.org/project/loopercli/

**Comment by vreuter** [comment]
:trophy: 

> https://pypi.org/project/loopercli/
