### ISSUE TITLE
summarizer needs a way to collapse large entities

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#114]
for example, in this project there are 30 input files in the data source column. it makes the html summary unusable.

![screenshot from 2019-03-05 17-34-27](https://user-images.githubusercontent.com/5271009/53842293-076bc800-3f6d-11e9-83a1-b0464862fd4f.png)

@aaron-gu do you have any idea for this? I know you thought about this in the past but I don't know what we decided.

**Comment by aaron-gu** [comment]
I thought I addressed this with d0e081166a0aa97809af73c96620393ee0dca16f, which just removed everything after 17 characters. Could you check if the footer contains the javascript code:

```
$(document).ready(function() {
            $('#data-table').DataTable({
              scrollX: true,
              fixedColumns: {
                leftColumns: 1
              },
              columnDefs: [ 
              {
                targets: 0,
                render: $.fn.dataTable.render.ellipsis(1000, true)
              },
              {
                targets: '_all',
                render: $.fn.dataTable.render.ellipsis(17, true)
              }
              ]
            });
          } );
```

**Comment by nsheff** [comment]
No, I don't have the `columnDefs` part, just the earlier stuff -- so it pre-dates this commit.. But I am using looper 0.11.0-dev -- why is it not doing that, then?

**Comment by nsheff** [comment]
ok I think it was a caching issue, because when I restarted, things are correct...not sure what happend. sorry to bother.
