### ISSUE TITLE
submission scripts are not printed

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#116]
when running with `lump`, the submission script paths are no longer printed to console.

**Comment by nsheff** [comment]
actually this is universally true, not just when `lump` is used.

**Comment by vreuter** [comment]
Runnning with `--dry-run` or no?

**Comment by nsheff** [comment]
dry run prints them, but real run does not.

**Comment by vreuter** [comment]
OK, if you pull `dev` and rerun, can you indicate whether https://github.com/pepkit/looper/commit/7a663ea1328b0e4b3079af368c57c9052e87736e fixes this, and if you'd like the messaging changed from what's provided there?

**Comment by nsheff** [comment]
Now it's printing "command count Creating submission script; command count: 1" after every one...
how did this get messed up? weird.

**Comment by vreuter** [comment]
> Now it's printing "command count Creating submission script; command count: 1" after every one...
> how did this get messed up? weird.

That didn't change with the most recent commit; it did that on the previous commit also.

**Comment by nsheff** [comment]
yeah, i looked at the commit so that must be true... but it wasn't. i may not have been using the latest commit, then.

**Comment by vreuter** [comment]
Spin-off issue is https://github.com/pepkit/looper/issues/117
