### ISSUE TITLE
"command count Creating submission script; command count: 1"

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#117]
https://github.com/pepkit/looper/issues/116#issuecomment-470209390

@nsheff do you want this changed, removed, or left as-is?

https://github.com/pepkit/looper/blob/dev/looper/submission_manager.py#L433

The logging call was introduced in https://github.com/pepkit/looper/commit/5c464ef4816941baf3e1edac9fd39567bec12853#diff-2564db5b270900750f35717dd808a157 and unmasked in https://github.com/pepkit/looper/commit/eb9e309b731cee373a393e23739498c02e009291#diff-2564db5b270900750f35717dd808a157

**Comment by nsheff** [comment]
sorry I didn't catch that you self-assigned -- I made the change I wanted

**Comment by vreuter** [comment]
No problem
