### ISSUE TITLE
looper summarize HTML issues

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#122]
I have a project with 244 samples. When there are more than 10 samples, the table is split into multiple pages. That's fine in theory, but this causes the "plottable columns" to only plot 10 samples.

The "plottable columns" should clearly plot all the columns, not just the 10 showing.

**Comment by aaron-gu** [comment]
Since it plots a bar graph with all of the samples on the x-axis, would it make the chart too messy?

This issue also brings up whether we should be accessing the PEP data to create the table instead of generating it in the html_reports.py file.

**Comment by nsheff** [comment]
no, you can put 250 bars into a bar chart no problem.

one way or another we'll have to print the data to HTML though... we have talked about this before if I remember right. I think it would be to just use the tsv file that is spit out, and load that with javascript, right?

**Comment by aaron-gu** [comment]
I added this feature to the Jinja branch. Python passes the tsv file as JSON through one of the template variables, which JavaScript is able to read and parse. Can you also test this to see if it works on the 244 samples?
