### ISSUE TITLE
numeric sample names have commas added (sometimes)

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#123]
It's nice that numeric columns get columns added automatically; but this shouldn't happen to a sample name. also it's strange that it's intermittent. some samples get changed but not others.

![Screenshot from 2019-03-12 08-32-35](https://user-images.githubusercontent.com/5271009/54200339-8bf4a400-44a1-11e9-8515-d894bfb1216f.png)

this also messes up the link to the same page.

**Comment by aaron-gu** [comment]
Could you test this on the most recent commit? I wasn't able to find any obvious reasons for why it would put commas in specific samples, but what I changed was putting an additional backslash in front of backslashes in strings and removing escaped characters.

**Comment by nsheff** [comment]
This may have been solved by the latest updates to the table formatting. I will have to double-check on this project when I get a chance.
