### ISSUE TITLE
selectors on flags

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#126]
recently we implemented `selector-attribute`, `selector-include` and `selector-exclude`.

It struck me that we might want to include/exclude based on job run status (flags).

For example, in #6, I just implemented `looper rerun` -- all this does it check for `failed` flags and only run those. this could be made more general... for example, now I want to run `looper destroy` only on samples with `failed` flags.

would it be possible to piggyback on the `selector` code to do this? Possibly by passing `selector-flag` instead of `selector-attribute` ? Then `selector-include` would operate on flags instead of attributes and I would say:

```
looper destroy --selector-flag failed
```

and `looper rerun` would then just be an alias to `looper run --selector-flag failed --ignore-flags`

**Comment by nsheff** [comment]
found another situation where this would be useful just now. I want to re-submit all jobs listed as 'running' (since the flag is broken)... no easy way to do that.

**Comment by nsheff** [comment]
+1 it bites me again :)

**Comment by donaldcampbelljr** [comment]
I think the best place to do this is in `fetch_samples` where we could pass a new argument `selector_flag`.

**Comment by donaldcampbelljr** [comment]
on `dev_126_selectors_on_flags`,

Can now fetch samples via: 
**Exclusion** 
`looper run --looper-config .looper.yaml --exc-flag "failed"`
`looper run --looper-config .looper.yaml --exc-flag ["failed", "completed"]`

**Selection**
`looper run --looper-config .looper.yaml --sel-flag "running"`
`looper run --looper-config .looper.yaml --sel-flag ["running", "completed", "waiting"]`

Can also use these in tandem with the select attributes arguments, e.g.:
`looper run --looper-config .looper.yaml --sel-flag ["running", "completed", "waiting"] --sel-attr "random_attr" --sel-incl ["something"]`

Still need to review pytests, check re-running failed samples, update the docs.
