### ISSUE TITLE
use Jinja2 templates in html_reports

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/looper#127]
`looper` should use Jinja2 templates to produce the summary files in the `html_reports.py`. This will enable `caravel` to reuse this code (https://github.com/pepkit/caravel/issues/84).

**Comment by nsheff** [comment]
this is going to be great -- does it look like it's pretty straightforward?

**Comment by michalstolarczyk** [comment]
I wouldn't say that it is straightforward, but it will be definitely much more flexible and transparent

**Comment by michalstolarczyk** [comment]
The switch to jinja templates in the reporting seems to be complete.
