### ISSUE TITLE
Suggestion: bit more of a nudge toward pypiper

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#13]
We could seize opportunity in the README to do a little shameless plug for `pypiper`. Right now it's mentioned as an original use case, but we could have a half- or one-sentence bit about why `pypiper` is good and could be of use if you're using `looper` for command-line tools. It's already a big plus that `pypiper` is linked here, but as a hypothetical user/reader, my mindset would be something like, "Hmm, here's a link, but that may entail substantial reading/digging to get a sense for what's there." If I saw a brief mention of what it was right there by the link, I'd be significantly more likely to click through and investigate.

**Comment by donaldcampbelljr** [comment]
We are currently re-working all of the documentation to live in one place. 
WIP here: https://pepkit.github.io/pep-docs/
We have a section in Looper FAQ that discusses (very briefly) the differences between Looper and Pypiper: https://pepkit.github.io/pep-docs/looper/faq/#whats-the-difference-between-looper-and-pypiper

Therefore, I'm going to close this issue for now. Let me know if you feel there should be even more detail explaining the differences between the two.
