### ISSUE TITLE
HTML reports assumes nonempty log glob

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#130]
It looks like there are a couple of spots in the HTML reporting module where we assume that there's a match for a `*log.md`. This can hit an `IndexError` if there's no match. Can we more cleanly handle that case, or prove guarantee of a match?

Linking the lines to `master` since it's more stable, but the analogous lines look to exist on `dev` also, albeit maybe in different locations:
https://github.com/pepkit/looper/blob/master/looper/html_reports.py#L871
https://github.com/pepkit/looper/blob/master/looper/html_reports.py#L1111

**Comment by michalstolarczyk** [comment]
I'm currently working on #127 which will influence the HTML generation in `looper`, so this problem might disappear. I'll keep my eye on that

**Comment by michalstolarczyk** [comment]
It's safer now. In case any of the files is missing `None` is returned and then it is handled at the HTML creation by the template

**Comment by vreuter** [comment]
> It's safer now. In case any of the files is missing `None` is returned and then it is handled at the HTML creation by the template

:raised_hands: sounds great
