### ISSUE TITLE
force yes in Cleaner

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/looper#131]
Why does the `--force-yes` option not influence the `Cleaner` call?

https://github.com/pepkit/looper/blob/2fea256b7278198f1211656dad27f1ef7e92c305/looper/looper.py#L156-L159

compare with `Destroyer` where we take that into consideration:

https://github.com/pepkit/looper/blob/2fea256b7278198f1211656dad27f1ef7e92c305/looper/looper.py#L197-L201

This makes the `looper clean` invalid in `caravel`

**Comment by vreuter** [comment]
In build_parser we only add that option to the destroy subparser.

**Comment by michalstolarczyk** [comment]
should we add it to clean subparser, then?

**Comment by vreuter** [comment]
That’s fine with me

**Comment by nsheff** [comment]
yes.

**Comment by michalstolarczyk** [comment]
Added on branch `jinja`
