### ISSUE TITLE
Parser + caravel

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#148]
In the `parser_types` functions, there's a `caravel` flag that's never `True` in `looper`, and it looks like those functions are unused in `caravel`. Does that need to be kept?

**Comment by michalstolarczyk** [comment]
> Does that need to be kept?

Yes, these are crucial in `caravel` and are used here (with `caravel` flag set to `True`):

https://github.com/pepkit/caravel/blob/64f3b36f5a49c8faad2d8ccb4058951dda89f03f/caravel/looper_parser.py#L85

**Comment by vreuter** [comment]
OK
