### ISSUE TITLE
Move caravel functionality to caravel

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#149]
```Caravel server encountered exception(s):

    Exception: Checked flag is only valid in caravel context

```

```
[2019-03-28 17:41:31,411] ERROR in caravel: Unhandled Exception: Checked flag is only valid in caravel context
Traceback (most recent call last):
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/caravel/caravel.py", line 100, in decorated
    return func(*args, **kwargs)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/caravel/caravel.py", line 284, in process
    actions = get_positional_args(blp(), sort=True)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/__init__.py", line 305, in build_parser
    action=_StoreBoolActionType, default=True, type=html_checkbox(checked=True),
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/parser_types.py", line 35, in html_checkbox
    raise Exception("Checked flag is only valid in caravel context")
Exception: Checked flag is only valid in caravel context
```

using latest dev caravel and jinja looper.

**Comment by nsheff** [comment]
```
[ns5bc@udc-ba35-36:~] looper check conf.yaml --sp atac -R
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 11, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 748, in main
    parser = build_parser()
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/__init__.py", line 305, in build_parser
    action=_StoreBoolActionType, default=True, type=html_checkbox(checked=True),
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/parser_types.py", line 35, in html_checkbox
    raise Exception("Checked flag is only valid in caravel context")
Exception: Checked flag is only valid in caravel context
```

**Comment by michalstolarczyk** [comment]
This problem arose after addition of this assertion:

https://github.com/pepkit/looper/blob/81b22459b67e4114d7901c8d10ce70a1d0b53c56/looper/parser_types.py#L33-L35

I think it can be at least degraded to a warning/info as the `checked` value set here:

https://github.com/pepkit/looper/blob/81b22459b67e4114d7901c8d10ce70a1d0b53c56/looper/__init__.py#L305

is needed in `caravel`

**Comment by nsheff** [comment]
well, that's causing failure in looper without caravel and in caravel...

**Comment by vreuter** [comment]
What’s checked do?

**Comment by michalstolarczyk** [comment]
determines whether the checkbox should be checked when the form is created. Just like the 
```
min_val=0, max_val=10, step=1, value=0
```
indicate the slider parameters in `html_range`

**Comment by michalstolarczyk** [comment]
and it is just disregarded if `html_checkbox` is used outside of caravel context `caravel=False`

**Comment by vreuter** [comment]
So why is something related to the web interface being set in `looper` itself? `looper` shouldn't know about `caravel`.

**Comment by michalstolarczyk** [comment]
> So why is something related to the web interface being set in looper itself

I consider it not related to the web interface but to the default `looper` options

There's no other way to create the form elements systematically in `caravel` than reading the required information from `looper`. And we decided to pass these data using the parser types: https://github.com/pepkit/looper/issues/92

**Comment by vreuter** [comment]
OK, can you point in `caravel` to where the value of `checked` becomes relevant, and then also where it's relevant within `looper`?

**Comment by michalstolarczyk** [comment]
> it is just disregarded if html_checkbox is used outside of caravel context

so it's is totally not relevant within looper. These functions in `parser_types` behave like python's builtin types by default. 

In `caravel` the parameters passed this way are processed by these lines:

https://github.com/pepkit/caravel/blob/0e39686e4c6221bff8ce9c0271b7a6f275641587/caravel/looper_parser.py#L89-L91

and then used in the templates for the HTML form composition

**Comment by nsheff** [comment]
the way I think of it, these new types we're defining are universal. they are not caravel specific... they are useful for any tool that would want to build a web interface. So, ideally they could go into a third package, 'webtypes', and importing that package could make looper 'web-friendly'. 

but, let's just stay on the side of practicality here and put them in looper so we don't have to solve all the world's problems.
