### ISSUE TITLE
downgrade logger info

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#156]
I want to downgrade this message printout because I don't think it's necessary:

https://github.com/pepkit/looper/blob/ee33a507d93f5ff5f52381e61b379b32314d7b8c/looper/looper.py#L840

any objections?

**Comment by nsheff** [comment]
These to `info` calls are also redundant: 

https://github.com/pepkit/looper/blob/ee33a507d93f5ff5f52381e61b379b32314d7b8c/looper/looper.py#L240-L244


You can see the flags checked right below. I would like to remove them
```
Using subproject: 'atac'
Setting sample sheet from file '/sfs/qumulo/qhome/ns5bc/code/dura_macs/metadata/annotations/atac.csv'
Results subdir: /sfs/lustre/allocations/shefflab/processed//dura_macs/results_pipeline
Checking project samples for flags: completed, failed, partial, running, waiting
COMPLETED: 9
FAILED: 0
PARTIAL: 0
RUNNING: 0
WAITING: 0
COMPLETED (9):
```

**Comment by vreuter** [comment]
No

**Comment by vreuter** [comment]
> I want to downgrade this message printout because I don't think it's necessary:
> 
> [looper/looper/looper.py](https://github.com/pepkit/looper/blob/ee33a507d93f5ff5f52381e61b379b32314d7b8c/looper/looper.py#L840)
> 
> Line 840 in [ee33a50](/pepkit/looper/commit/ee33a507d93f5ff5f52381e61b379b32314d7b8c)
>  _LOGGER.info("Results subdir: " + prj.metadata.results_subdir) 
> 
> any objections?

No

**Comment by vreuter** [comment]
I have no preference about the level of any messages.
