### ISSUE TITLE
Lengthy table loading in summary

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/looper#157]
The table in the index page takes extremely long to load in large projects. I'm testing it on a project with +400 samples and it took ~10minutes. 

It's probably due to the recent changes in JavaScript table processing

**Comment by michalstolarczyk** [comment]
nvm

**Comment by nsheff** [comment]
what was wrong??

**Comment by michalstolarczyk** [comment]
my totally unrelated local fix to other issue turned out to be totally related

**Comment by nsheff** [comment]
:laughing:
