### ISSUE TITLE
clarify docs on create_navbar_links function

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#160]
https://github.com/pepkit/looper/blob/074f676d026410f1feb0d688e4618a76ba8900df/looper/html_reports.py#L136-L137

what is `stats`? A list?

Stats should be a pandas.DataFrame I think, analogous to how `objs` is handled here. (maybe?)

**Comment by michalstolarczyk** [comment]
clarified with ec2e992154f00e70baebcbc270b39a9125f5512b. `stats` is a list of `dict`s
