### ISSUE TITLE
Status for resubmissions

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#169]
Right now, if a submission that's been run and failed (and therefore has the corresponding flag) is rerun, then a `looper check` result for any job that's remains pending resubmission will still be `FAILED`. We could eagerly in `looper` remove the failed flag for such submissions rather than waiting for `pypiper` to do it upon submission, so that the status would be more accurate (`WAITING`, then?) Is this worth it, though?

**Comment by nsheff** [comment]
Related to #63  

What we really need is a formal defined specification for communicating about job status, which looper could then take advantage of.

**Comment by donaldcampbelljr** [comment]
I believe we could do this during a `rerun` but only if we have pipestat configured. We could then call `pipestat.set_status` to do this for us as sample is added for `rerun`. 

Is this desirable?

Right now, Looper is only reading flag files, not setting them: https://github.com/pepkit/looper/issues/326

**Comment by donaldcampbelljr** [comment]
OK, I decided to go with having pipestat set the status to `waiting` upon rerun.
