### ISSUE TITLE
Reduce error message verbosity

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#171]
Here is a really painful 4-line error message from 1 missing attribute:

```
## [1 of 15] Sample_1 (ATAC)
Missing and/or empty attribute(s).: Missing: read1; Empty: 
> Not submitted: Missing and/or empty attribute(s).: Missing: read1; Empty: 
Error (missing attribute): 'pepatac.py' requires sample attribute 'read1' for option/argument '--input'
> Not submitted: Required attribute(s) missing for pipeline arguments string
```

**Comment by nsheff** [comment]
It appears we're checking for missing attributes twice, one in peppy and then again in looper, which is what's leading to this.

In peppy:

https://github.com/pepkit/peppy/blob/ef4c8d9caac3b5d0c7795b4ce7d44b715605254a/peppy/sample.py#L212-L238

in looper:

https://github.com/pepkit/looper/blob/48cb76e2ac777ab4209e489a94db41707b9149da/looper/pipeline_interface.py#L287-L294

would be great if we could consolidate this check... but maybe there's a reason we're doing it like this?

**Comment by vreuter** [comment]
@nsheff I'm working on a feature branch and will include it there if that's alright?

**Comment by nsheff** [comment]
Sure that would be great

**Comment by vreuter** [comment]
Addressed with changes in https://github.com/pepkit/looper/pull/175 though will await real-world anecdotal evidence to close, as additional tweaks may emerge or be otherwise needed
