### ISSUE TITLE
compute settings from pipeline interface are no longer populated

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#184]
`compute` settings from the pipeline interface are apparently no longer being populated by the submission scripts

Could be related to https://github.com/pepkit/looper/issues/54

**Comment by nsheff** [comment]
section in question: https://github.com/databio/pepatac/blob/a0e4347b199c91bbfd7d994b0705da2ca8d51015/pipeline_interface.yaml#L31-L33

**Comment by vreuter** [comment]
For these sorts of issues, a use case (i.e., project files) is helpful for assessment. Essential, actually.

**Comment by vreuter** [comment]
Also hopefully you're on `master`; I'd expect `dev` to be nonfunctional in a variety of ways at the moment.

**Comment by vreuter** [comment]
Also there's an open question in #54 that's blocking resolution.

**Comment by nsheff** [comment]
use case: try to run latest pepatac with latest looper, on singularity.

**Comment by vreuter** [comment]
With `dev` on `divvy`, `peppy`, `looper`, and `pepatac` (and `attmap` 0.12.3), this now appears resolved for me. From Python 2 on Rivanna:
```
looper run -d $HOME/code/pepatac/examples/test_project/test_config.yaml --compute-package singularity_slurm
```
yields the attached submission script (home path replaced).
[test_pepatac.txt](https://github.com/pepkit/looper/files/3198752/test_pepatac.txt)

**Comment by vreuter** [comment]
Word of caution...submission script tests aren't running on 2.7--which is odd since this use case produces a submission script--but just be aware that there may be some yet-unresolved corner case behavior, though it seems likely that it's specific to design in the test suite itself rather than in the main package.

**Comment by nsheff** [comment]
awesome. thanks! I think this is worth a point release...

**Comment by nsheff** [comment]
but yeah it seems we should double-check that 2.7 is working since that's still where everything is used mostly at this point
