### ISSUE TITLE
How to Configure for a Front end projects ( ReactJS/NodeJS)

### ISSUE THREAD

**Issue by Venmathi2510** [pepkit/looper#188]
Hello Team,
I would like to understand whether looper can be used for front end projects deployment and if yes, some steps on it would be a great help.

**Comment by nsheff** [comment]
Hi @Venmathi2510, can you please be more specific in your question? The documentation is here: http://looper.databio.org/en/latest/

**Comment by nsheff** [comment]
I think you may be interested in [caravel](http://caravel.databio.org/en/latest/), which is our front-end interface to submitting projects... it does not use ReactJS or NodeJS (it uses flask). You could potentially use something else with looper, but we aren't doing that actively.

does that answer your question?

**Comment by nsheff** [comment]
Hi @Venmathi2510 I'm closing this issue, please reopen if you have something to add.
