### ISSUE TITLE
Summarize does not handle more than one figure reported per sample

### ISSUE THREAD

**Issue by afrendeiro** [pepkit/looper#19]
Then current implementation of the html figure report does not handle more than one figure reported per sample.
I will post a PR today for this.

**Comment by nsheff** [comment]
Are you sure? I think it does, as long as they have different keys -- it would not allow more than 1 figure with the same key, which is what it's supposed to do...

I thought it was behaving exactly the way `report_result` behaves...

**Comment by afrendeiro** [comment]
Not in my use cases, and yes with different keys.
Either way, if you can have a look at #20, it would be great.

**Comment by nsheff** [comment]
@afrendeiro, with the new `report_figure` functionality, I believe this is fixed, so I'll close this issue. feel free to reopen if you're still having trouble.
