### ISSUE TITLE
required executables

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#195]
It would be nice if a pipeline could specify what executables it needs.

This could happen in the `pipeline_interface` -- a  new attribute called `required_executables`, and perhaps a second called `required_config_executables`, could be read by looper, which could test these executables to make sure they are in the PATH.

**Comment by nsheff** [comment]
with #225 we've now started validating PEPs according to a schema. This issue is about making sure the pipeline can run; in a sense, validating an *environment*. 

Does it make sense to do something similar? Define an environment schema, and then validate that?

**Comment by donaldcampbelljr** [comment]
some thoughts:
write a schema to define executables (JSON schema format), write a validation program to validate the computing environments.
