### ISSUE TITLE
Looper not passing right path to --sample-yaml

### ISSUE THREAD

**Issue by afrendeiro** [pepkit/looper#198]
For some reason even though my sample objects are of base class `Sample`
the `type(self) is Sample` statement is evaluating as `False`:
https://github.com/pepkit/peppy/blob/master/peppy/sample.py#L238

I then end up with a `--sample-yaml` argument passed to my pipeline that has the form `<sample_name>_Sample.yaml`.

This must be happening only when getting the arguments to pass to the pipeline:
https://github.com/pepkit/looper/blob/master/looper/pipeline_interface.py#L283
and not when serializing the Sample: https://github.com/pepkit/looper/blob/master/looper/looper.py#L387
because the actual yaml file is written in the form `<sample_name>.yaml`.

**Comment by vreuter** [comment]
Thanks for reporting @afrendeiro . So then is some sort of exception relating to a nonexistent sample YAML file thrown, since then the pipeline looks for the `_Sample.yaml` one that doesn't exist rather than the ordinary `.yaml` one that does exist?

**Comment by afrendeiro** [comment]
Yup, my pipeline is failing since it doesn't find the yaml file passed with the `--sample-yaml` option.

**Comment by vreuter** [comment]
This will be fixed in a point release. My guess is that the instances are of type `peppy.Sample` and that conditional is checking for `looper.Sample`

**Comment by afrendeiro** [comment]
Ah, that would make sense. Thanks!
