### ISSUE TITLE
--compute and --compute-package docs

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#204]
```
looper run --help shows:
```

```
  --compute COMPUTE_PACKAGES
                        YAML file with looper environment compute settings.
  --compute-package COMPUTE_PACKAGES
                        YAML file with looper environment compute settings.
```

From: 

https://github.com/pepkit/looper/blob/68a9c222dc54c1ab2ccd28852a6c1aaa7371d0f1/looper/__init__.py#L150-L157

This obviously doesn't make sense... Does anyone know where the new `compute-package` option came from, and why these are listed as "YAML files" ? Is there a change underway that I'm not aware of?

**Comment by vreuter** [comment]
Well, these the 2 relevant commits:
https://github.com/pepkit/looper/commit/c2fd06f8bb6c0e6d8364864bebb690a4f3423b72
https://github.com/pepkit/looper/commit/5da577070ccd63fd273d73ab7c77078502781023

Unfortunately I used a poor message --"use more `divvy`"-- that's merely a hint and is pretty unclear. The option name intends to reflect the naming used in `divvy`, introduced in https://github.com/pepkit/divvy/commit/80c0f845983b6d990fb99e86590f6ec94440e0e2, especially lines 163-170 of what used to (in that commit) be `divvy/divvy.py`.

What should the help messages instead say?

**Comment by nsheff** [comment]
ah! so are you intending it to be like `--compute-package PACKAGE` to change the way we're currently doing it (`--compute PACKAGE`) ? And then `--compute DIVCFG` is a way to pass a divvy config?

I like that. Unfortunately it wouldn't be backwards compatibile and the `--compute` syntax is ubiquitous.

I'd instead elect: `--compute` stays, and then add `--divcfg` for the on-the-fly config option, if that's what you meant... then the help message obviously shouldn't say "YAML" for the package one...

or did I misunderstand?

**Comment by nsheff** [comment]
actually thinking about it some more -- if python has partial completion, then this would work:

- change the old  `--compute` to  `--compute-package`. Now, saying `--compute `will still match `compute-package`, so old code will work.
- don't introduce a new `--compute` arg like we have in dev, because that precludes the above. Instead, use `--divcfg` as a way to specify the divvy config file on the fly.

what do you think?

**Comment by vreuter** [comment]
I don’t know what “the —compute syntax is ubiquitous” means. People are frequently programmatically using the CLI?

**Comment by nsheff** [comment]
or I'm just used to it :). and that the docs for many tools, pipelines, etc say `--compute`.  for example we'd have to dig up every tutorial that uses looper with compute, like this one:

http://pepatac.databio.org/en/latest/howto/download/#32-convert-sra-files-to-bam

just in random places. anyway I don't see a problem with changing it in the way I said, which keeps `--compute-package` because `--compute` should populate that... as long as we don't specify somethign *else* as compute.

in general I just think it's not good practice to replace a several year old parameter with another one with the same name, that does something different. it's going to cause confusion.

**Comment by vreuter** [comment]
They’re intended to be equivalent and hence alter nothing about use of —compute, which is why they have the same help message (albeit a wrong one).

**Comment by vreuter** [comment]
Basically, `--compute-package` is introduced to allow a user to communicate the desired compute package name to `looper` with a (IMO) less ambiguous term.

**Comment by nsheff** [comment]
I see, I did not realize that. Then why not just take out the `--compute` one? It will just go to `--compute-package` automatically because the string matches.

**Comment by nsheff** [comment]
See: 
```
sheffien@nox:~/code/divvy$ divvy --vers
divvy 0.3.4
sheffien@nox:~/code/divvy$ divvy --versio
divvy 0.3.4
sheffien@nox:~/code/divvy$ divvy --version
divvy 0.3.4
```

**Comment by vreuter** [comment]
> I see, I did not realize that. Then why not just take out the `--compute` one? It will just go to `--compute-package` automatically because the string matches.

OK, done.  I suppose this could affect something with `caravel` depending on how the CLI option names are used there, but hopefully if this change does necessitate one there it's relatively localized.

**Comment by nsheff** [comment]
cool thanks.

caravel doesn't use the command line interface anymore, it calls functions directly.
