### ISSUE TITLE
protocol mappings broken

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#21]
Looper version 0.8 has a problem; with the RNA-seq pipeline, for example, it gives the error of `No mapping for protocol: 'rnaKallisto'` even when there *is* a mapping for such a protocol.

I think something to do with implementing the catch-all asterisk may have broken the mapping code, or something. For a reprex look at the rnapipe pipeline.

reported by @aaron-gu

**Comment by nsheff** [comment]
You can reproduce this error by cloning https://github.com/databio/rnapipe and running:
```
cd examples
looper run test_config.yaml -d
```

**Comment by nsheff** [comment]
@vreuter we're looking at this but it might be a really easy thing if you took a quick look -- can you shed any light on this?

As is I think looper 0.8 is not usable, which is not good --  is it working for you?

**Comment by vreuter** [comment]
I saw this over the weekend and investigated but a solution didn't emerge. `self.interfaces_by_protocol[protocol]` should probably wrap `protocol` as `alpha_cased(protocol)`, though; it looked like that was one issue. That didn't totally solve it, though. I'll revisit this soon.

**Comment by nsheff** [comment]
have you run into this problem with any of your stuff? or are you still using 0.7.2?

**Comment by vreuter** [comment]
I added the LSF option but haven't yet used it, so I've not run into it but also haven't exactly been a power user lately. That said, I'd thought that I'd run a couple things there with v0.8 and not had any issue, but it's possible that was still with a previous version.

**Comment by vreuter** [comment]
Oh and to clarify my earlier comment...I mean I think it should be `self.interfaces_by_protocol[alpha_cased(protocol)]`.

**Comment by nsheff** [comment]
Fixed in #22
