### ISSUE TITLE
Recover Mode

### ISSUE THREAD

**Issue by franceskoback-Gladstone** [pepkit/looper#229]
When  I try to run a certain pipeline with run looper I get an error that ends in: 

````
This indicates that another process may be executing this command, or the pipeline was not properly shut down.  If the pipeline was not properly shut down last time, you should restart it in 'recover' mode (-R) to indicate that this step should be restarted.
```` 
can anybody please inform me on how to restart the pipeline in recover mode?  When I run 
````
python open_pipelines/pipelines/atacseq.py \
-R
````
it gives me the following error: 
````
atacseq-pipeline: error: unrecognized arguments:  -R 
````
despite [-R] being an optional argument listed here 
````
usage: atacseq-pipeline [-h] [-y SAMPLE_CONFIG] [-p {macs2,spp}]
                        [--shift-reads] [--pvalue PVALUE]
                        [--qvalue QVALUE] [-S SAMPLE_NAME]
                        [-I INPUT_FILES [INPUT_FILES ...]]
                        [-I2 [INPUT_FILES2 [INPUT_FILES2 ...]]]
                        [-G GENOME_ASSEMBLY] [-Q SINGLE_OR_PAIRED]
                        [-C CONFIG_FILE] [-O PARENT_OUTPUT_FOLDER]
                        [-M MEMORY_LIMIT] [-P NUMBER_OF_CORES]
                        [-R] [-N] [-D] [-F] [-T] [--silent]
                        [--verbosity V] [--logdev]
````

**Comment by nsheff** [comment]
I believe you are doing it correctly. I can't explain why that pipeline is not accepting the `-R` flag. You are passing it the rest of the arguments it needs, right (not just `-R` as in your example)?

You can always just manually remove the `lock...` file in the output folder (and any broken intermediate file created by that step, and then it shouldn't need to recover...

This is really a pipeline question, though. If you pass the` -R` to looper it will pass it through to the pipeline.
