### ISSUE TITLE
looper collate

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#238]
We've repeatedly recognized the challenge that while looper excels at running sample-wise commands, it lacks a project-wise command. Custom summarizers made this possible, but they didn't run through divvy, leading to compute issues. To address this, I propose a new capability called `looper collate` (name open for discussion).

collate subsumes the current 'custom summarizers' idea, with a few key differences:

1. it employs a command template, making it more flexible (you can put any command in there)
2. it runs the command through divvy, just like `looper run`, instead of inflexibly locally, like `looper summarize`.

The difference between `collate` and `run` is:

1.  the collate template does not have access to the sample namespace (as it is intended to be run on the project).
2. the collate command does not make use of `protocol_mappings`, which is sample-specific. Instead, it would require an identifier passed either on the command line or in the project config, which maps the project to a collator.

Implementing it should be fairly straightforward; it would use all the same functionality as `run`.

## how do we encode a collator in the pipeline interface?

I've thought of putting the collator settings in many different places in the pipeline interface. in the end, I realized it needs many of its own settings, sharing essentially nothing from the pipeline configuration, so it actually makes the most sense as a separate section altogether. 
Here's a possible way to encode this in a pipeline interface:

```
protocol_mappings:
  ATAC: pepatac.py

pipelines:
  pepatac.py:
    name: PEPATAC
      path: pipelines/pepatac.py
      schema: https://schema.databio.org/pipelines/pepatac.yaml
      output_schema: https://schema.databio.org/pipelines/pepatac_output.yaml
      command_template: >
        {pipeline.path}
        --sample-name {sample.sample_name}
        --genome {sample.genome}
        --input {sample.read1}
        --single-or-paired {sample.read_type}
        -O {looper.output_folder}
        -J {looper.job_name}
        -P {looper.cores}
        -M {looper.mem}
        {% if sample.read2 is defined %} --input2 {sample.read2} {% endif %}
        ...

collator_mappings:
  ATAC: pepatac

collators:        
  pepatac:
    path: pipelines/pepatac_collator.py
    schema: https://schema.databio.org/pipelines/pepatac_output.yaml
    output_schema: https://schema.databio.org/pipelines/pepatac_project_output.yaml
    command_template: >
      { pipeline.path}  -c {looper.pep_config}
      -O {looper.output_folder}
      -P {looper.cores}
      -M {looper.mem}
    compute:
      bulker_crate: databio/pepatac
      size_dependent_attributes: collate_resources.tsv
```

A few things to note:

1. the collator has its own `compute` section. Thus, it could specify its own bulker crate, docker container, etc. Or, it can just re-use the other one. It can also specify its own `size_dependent_attributes` file. It makes sense to me to specify separate of these, since the collator has **very** different tool requirements and resource requirements.
2. in this example, I've outsourced the `resources` into the new way (#236)
3. I've outsourced the 'outputs' section and the 'summary_results' section to 'output_schema' (#237). This really nicely illustrates the new parallel structure provided by that idea... 'summary results'  is no longer any different from outputs, it's just the output of a collator instead of a pipeline.
4. Notice that the pipeline's `output_schema` can be identical to the collator's `schema` (input schema -- should be renamed?).

in this setting, collators and pipelines operate almost identically. a collator is almost just another pipeline... it just has the 2 differences noted above: it runs on a project, not on a sample; and so therefore it requires a project-level mapping attribute

**Comment by vreuter** [comment]
This all sounds great. One thing I'm confused by though is the `collator_mappings`. Here it looks like a protocol mapping to pipeline.

**Comment by nsheff** [comment]
well, it's the same idea, it's just happening at the project level (so "ATAC" in this case is a project attribute, not a sample attribute), and it maps to a collator, not to a pipeline (which just differs in which section they're in on the piface)

**Comment by jpsmith5** [comment]
Generally speaking, I'm totally on board with this plan. Not sure I love `collate`, but currently don't have a great alternative. Could just be that `run` feels all encompassing, instead of sample specific, so that `collate`, feels off, since it also is "running" something, just a project level run instead of a sample level run. Is it worse to have `looper run` default to running samples, but pass a flag to run a project? For example: `looper run <project_config.yaml> --project`... or `--type project` vs `--type sample`

Re: A few things to note:

4. What about 'native/raw/pre/in_schema' and 'processed/post/out_schema', or something along those lines, versus input_schema(schema) and output_schema.? Just spitballing.

**Comment by nsheff** [comment]
What is the project-level variable that's used for the `collator_mappings` ? Is it `protocol`? Should we un-overload that?

**Comment by nsheff** [comment]
> Could just be that run feels all encompassing, instead of sample specific, so that collate

What about making it `looper run --project` with alias `looper runp` ?

**Comment by nsheff** [comment]
We decided to go with `looper runp`.

And for the mappings question, this has been solved after extensive debate with a new, pep-based implementation reached in #244.
