### ISSUE TITLE
Clarify that the required `sample_name` attribute cannot include spaces

### ISSUE THREAD

**Issue by jpsmith5** [pepkit/looper#249]
Not sure if we should address this, but it will break if the `sample_name` attribute includes spaces, as `looper` is then capturing only up to the first space when trying to submit the submission script.  

If we would never expect spaces, could just add a comment in the docs regarding this?

**Comment by stolarczyk** [comment]
good catch. I think it should be handled in the code, documenting this is not enough. Let's be honest, most of the users will not read _all_ the docs...

We have two options then

1. add a `pattern` for the `sample_name` in the schema: https://json-schema.org/understanding-json-schema/reference/regular_expressions.html
2. catch that in even earlier, in `peppy`
