### ISSUE TITLE
`toggle` functionality removed?

### ISSUE THREAD

**Issue by jpsmith5** [pepkit/looper#251]
Did the `toggle` function get removed?

In testing, it no longer seems to be recognized. In this case, a column in the sample annotation file named toggle, with entries of either 0 or 1.

**Comment by stolarczyk** [comment]
yes, I _sort of_ unintentionally removed it because of this came to my radar: https://github.com/pepkit/peppy/issues/338

Current select samples functionality 
```
select samples:
  This group of arguments lets you specify samples to use by exclusion OR
  inclusion of the samples attribute values.

  --selector-attribute SELECTOR_ATTRIBUTE
                        Specify the attribute for samples exclusion OR
                        inclusion
  --selector-exclude [SELECTOR_EXCLUDE [SELECTOR_EXCLUDE ...]]
                        Operate only on samples that either lack this
                        attribute value or for which this value is not in this
                        collection.
  --selector-include [SELECTOR_INCLUDE [SELECTOR_INCLUDE ...]]
                        Operate only on samples associated with these
                        attribute values; if not provided, all samples are
                        used.
```
is less flexible than `toggle`, but the new one could replace both in a nicer way.

what do you think @nsheff @jpsmith5 , do we bring `toggle` back or implement `sample_filters`? I think I like the latter a bit more.

**Comment by nsheff** [comment]
dunno... the toggle idea is nice in a way because it persists. but that's also the problem with it... it requires a change to the sample sheet, which we should try to avoid...

**Comment by stolarczyk** [comment]
in fact `toggle` sample attribute can an implied/derived/appended one (similar to `pipeline_interface`).

We could also keep the old `toggle` functionality and just follow the pipeline_interface example:

1. make `toggle` a special attr
2. allow to change it in `looper:toggle_key`
