### ISSUE TITLE
Ideas for streamlining CLI

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#253]
A few ideas for making it easier to interact with looper on the CLI.

## project repositories

Would work like git. it's similar to our looper config idea, but happens at the repo level instead of globally.

```
looper init -c metadata/project.yaml 
```
creates a `.looper.yaml` file that points to the yaml pep

```yaml
pep: metadata/project.yaml
```

Now, `looper run` just knows what to do without passing `metadata/project.yaml`, as long as you're in that folder. You can still pass it if you want.

Maybe you can change the value on the CLI:

```
looper set-pep metadata/project.yaml 
```

## lpr

thoughts on changing the command from `looper` to `lpr` ?

**Comment by stolarczyk** [comment]
we have decided to go with a flat YAML `.looper.yaml`, where users can pre-set any command line argument, for example:

```yaml
config_file: cfg.yaml
dbg: False
limit: 2
lumpn: 2
```

implemented in https://github.com/pepkit/looper/commit/c884fafb357b3db674bc3c0248b3b780cb848e0c

naturally, the keys need to match the `dest` argument in `ArgumentParser.add_argument` method, which becomes a key in `argparse.Namespace` object. 

Apart from reading looper source code, there's no way to learn the possible settings to set in the dotfile. Therefore, I think, we need to provide a way to display them. I've already built necessary infrastructure in `ubiquerg` to list the possible keys:

```python
In [12]: parser = build_parser()                                                                                                                                                                          

In [13]: type(parser)                                                                                                                                                                                     
Out[13]: ubiquerg.cli_tools.VersionInHelpParser

In [14]: d=parser.dests_by_subparser()                                                                                                                                                                    

In [15]: d.keys()                                                                                                                                                                                         
Out[15]: dict_keys(['run', 'rerun', 'runp', 'summarize', 'destroy', 'check', 'clean'])

In [16]: d["run"][0:4]                                                                                                                                                                                    
Out[16]: ['ignore_flags', 'time_delay', 'package', 'compute']
```

Do we append this info to the auto-generated help? Or is this a separate subcommand? Making it separate would make sense if we planned to make it more powerful, e.g allow setting things from the CLI.

**Comment by stolarczyk** [comment]
went with: 

```
[mstolarczyk@MichalsMBP atac_ebna2](master): looper --dotfile-template
# looper dotfile path: /Users/mstolarczyk/Uczelnia/UVA/code/atac_ebna2/.looper.yaml

logfile: 'None'
verbosity: 'None'
logging_level: 'None'
dbg: 'False'
env: 'None'
ignore_flags: 'False'
time_delay: '0'
package: 'None'
compute: 'None'
limit: 'None'
pipeline_args: ''
lump: 'None'
lumpn: 'None'
config_file: 'None'
pifaces: 'None'
file_checks: 'True'
dry_run: 'False'
selector_attribute: 'toggle'
selector_exclude: 'None'
selector_include: 'None'
amendments: 'None'
```

**Comment by nsheff** [comment]
the note in the output is: "# looper dotfile path: /Users/mstolarczyk/Uczelnia/UVA/code/atac_ebna2/.looper.yaml
"

Seems to indicate it creates a file there; but it does not... why is this message in the dotfile, or did you intend to actually create that? or let me create it with `> .looper.yaml` ?

**Comment by nsheff** [comment]
"Path to a project configuration file is a required, provide it as a positional argument or in the looper dotfile in this directory (/home/nsheff/code/looper/.looper.yaml)" 

I don't know how to actually provide this... should it be something like "config: path/to/yaml.yaml" in .looper? It's confusing...

**Comment by stolarczyk** [comment]
> Seems to indicate it creates a file there; but it does not... why is this message in the dotfile, or did you intend to actually create that? or let me create it with > .looper.yaml ?

I did not intend to create the file. I'd expect users to use `>`. The comment in the file indicates where looper expects the file to be saved. We can remove this line if you find it confusing.

> I don't know how to actually provide this... should it be something like "config: path/to/yaml.yaml" in .looper? It's confusing...

There is an entry in the dotfile template that does it: `config_file `

**Comment by nsheff** [comment]
Got it. It works, I tweaked the error message. 

I found the `--dotfile-template` syntax a bit strange. Here are a few ideas:

- `looper dotfile` prints a new dotfile
- `looper dotfile pep.yaml` auto-populates `config_file` with `pep.yaml`
- instead of just printing, it actually creates `.looper.yaml` instead
- remove the comment in the top of the yaml file, no need to comment with its own path

Thinking a bit more;
- why `looper dotfile` instead of `looper init` ? so, why not just `looper init` instead of `looper --dotfile-template`, I guess?

**Comment by nsheff** [comment]
> I did not intend to create the file. 

Ok -- but why? do you think that's confusing for users? I think of it kinda like 'git init'... it creates the .git folder.

**Comment by stolarczyk** [comment]
as discussed, I implemented `looper init` that initializes the looper dotfile. One can change the default by the desired argument to the `init` command:
```
[mstolarczyk@MichalsMBP looper](dev): looper init test.yaml --package test_package --limit 1
Initialized looper dotfile in: /Users/mstolarczyk/Uczelnia/UVA/code/looper/.looper.yaml
[mstolarczyk@MichalsMBP looper](dev): cat /Users/mstolarczyk/Uczelnia/UVA/code/looper/.looper.yaml
logfile: None
verbosity: None
logging_level: None
dbg: 'False'
env: None
ignore_flags: 'False'
time_delay: '0'
package: test_package
settings: ''
compute: None
limit: '1'
command_extra: ''
command_extra_override: ''
lump: None
lumpn: None
config_file: test.yaml
pifaces: None
file_checks: 'True'
dry_run: 'False'
selector_attribute: toggle
selector_exclude: None
selector_include: None
amendments: None
```

**Comment by stolarczyk** [comment]
if the file already exists, looper does not overwrite it. 

But to solve https://github.com/pepkit/looper/issues/64 we could allow:

`looper init --modify <args>` 

That would change any args specified

**Comment by nsheff** [comment]
The `--modify` idea seems great.

but do you think `looper init --modify` is better than a new command like `looper mod` or something? It's not really *init*ializing anymore at that point

**Comment by nsheff** [comment]
Thought:

what if you do this:

```
cd my-project
looper init pep.yaml
cd subdirectory
looper run
```

it will fail because `.looper.yaml` is not in `subdirectory`. Should looper, like git, search for the `.looper.yaml` in parent folders?

**Comment by stolarczyk** [comment]
alright, I think we've got it

```
[mstolarczyk@MichalsMBP looper](dev): looper mod --package test
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/looper/looper.py", line 706, in main
    sys.exit(int(not write_dotfile(parser, dotfile_path(must_exist=True),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/looper/utils.py", line 348, in dotfile_path
    "its parents".format(LOOPER_DOTFILE_NAME, directory))
OSError: Looper dotfile (.looper.yaml) not found in '/Users/mstolarczyk/Uczelnia/UVA/code/looper' and all its parents
[mstolarczyk@MichalsMBP looper](dev): looper init 
Initialized looper dotfile: /Users/mstolarczyk/Uczelnia/UVA/code/looper/.looper.yaml
[mstolarczyk@MichalsMBP looper](dev): cd tests/smoketests
[mstolarczyk@MichalsMBP smoketests](dev): looper mod -p test_package
Modified looper dotfile: /Users/mstolarczyk/Uczelnia/UVA/code/looper/.looper.yaml
[mstolarczyk@MichalsMBP smoketests](dev): c ../../.looper.yaml 
logfile: None
verbosity: None
logging_level: None
dbg: 'False'
env: None
ignore_flags: 'False'
time_delay: '0'
package: test_package
settings: ''
compute: None
limit: None
command_extra: ''
command_extra_override: ''
lump: None
lumpn: None
config_file: None
pifaces: None
file_checks: 'True'
dry_run: 'False'
selector_attribute: toggle
selector_exclude: None
selector_include: None
amendments: None
command: mod
force_yes: 'False'
```

**Comment by nsheff** [comment]
Here's a radical idea: What if we eliminate the `looper` section of the PEP entirely, and only allow this `.looper.yaml` file?

Maybe that's a starting point for a new way to approach this...

**Comment by stolarczyk** [comment]
That's and interesting thought. One thing I don't like about this is that `.looper.yaml` becomes required since `output_dir` needs to be specified somewhere. Is there any way to circumvent that?

This will also require the dotfile to be hierarchical since current `Project.looper` contents will need to live in separately from the CLI arguments. But that's totally fine.

**Comment by nsheff** [comment]
> will need to live in separately...

unless the Project.looper (including output_dir) all become CLI args...

**Comment by stolarczyk** [comment]
well, can't find any downsides of that. It adds more flexibility since now the output_dir could be modulated in two places. 

current possible contents of `Project.looper` are:
- `output_dir`
- `pipeline_interfaces` (already a CLI arg)
- `pipeline_interfaces_key`
- `toggle_key` (can go away when we implement sample filters in `peppy` at some point)

**Comment by stolarczyk** [comment]
should we squeeze it in the upcoming release? It's a config format change after all.

**Comment by nsheff** [comment]
what if:
yeah I think we should solve this.

all looper options can be specified in 3 places:
1. CLI
2. `looper` section of a PEP
3. .looper.yaml

Ok...almost how we have it now, with the CLI expansion described above. Now, just make .looper.yaml format like this:

```
looper:
  output_dir: blah
  pipeline_interfaces: blah
```

This makes 2 and 3 become the same thing, just load `.looper.yaml` with peppy. That makes implementing it super simple.

**Comment by nsheff** [comment]
so in this case, `looper init pep.yaml` would create .looper.yaml with this info:

```
pep_version:2.0.0
project_modifiers:
  import: 
    - pep.yaml
```

That's it.

**Comment by nsheff** [comment]
I think this is kind of hijacking the utility of the pep2 for something it wasn't meant for. but it's just so useful...

conceptually I can think of this, as 'project modifiers' is really just enabling nested yamls. they can import, or contain other yamls. So, that's a useful generic concept. If that was spun off as its own capability separate from PEP, then that's all we really need here, not full PEP, just nested yamls.

**Comment by stolarczyk** [comment]
alright, I think it's ready

**Comment by nsheff** [comment]
does output dir need to be added to the CLI and looper section?

**Comment by stolarczyk** [comment]
Yeah. I forgot to add the output dir argument and adjust the corresponding Project property. But of course it’s meant to behave the same as other args.
