### ISSUE TITLE
toggle

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#263]
-toggle-key should be folded into selector attributes

-sel-attr defaults to 'toggle'
-sel-incl defaults to '1'

**Comment by donaldcampbelljr** [comment]
Currently:
```
sel_attr = {str} 'toggle'
sel_excl = {NoneType} None
sel_incl = {NoneType} None
toggle_key = {NoneType} None
```
However, per `looper run --help`:
`-g K, --toggle-key K               Sample attribute specifying toggle. Default: toggle`


Should we remove --toggle-key ?
