### ISSUE TITLE
.looper.yaml  should just use a relative path

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#267]
_Originally posted by @nsheff in https://github.com/pepkit/looper/issues/266#issuecomment-631562293_

requires 2 changes:

1. if we say `looper init x`, it should identify the relative path to config and use that. right now it's sticking in an absolute path

2. if you say `looper run` from a subdir, it's assuming a relative path in .looper is relative to `pwd`. instead, it should consider it relative to `.looper.yaml`.

**Comment by stolarczyk** [comment]
this should make this work as expected

**Comment by nsheff** [comment]
this doesn't solve point 2 though, does it? only point 1 (plus env vars)?

**Comment by stolarczyk** [comment]
I thought it did. Isn't this what you meant?
```
[mstolarczyk@MichalsMBP bedstat]: looper init test_bedstat.yaml 
Initialized looper dotfile: /Users/mstolarczyk/Desktop/testing/bedstat/.looper.yaml
[mstolarczyk@MichalsMBP bedstat]: c .looper.yaml 
config_file_path: test_bedstat.yaml
[mstolarczyk@MichalsMBP bedstat]: cd subdir; looper inspect
No project config defined, using: /Users/mstolarczyk/Desktop/testing/bedstat/test_bedstat.yaml. Read from dotfile (/Users/mstolarczyk/Desktop/testing/bedstat/subdir/.looper.yaml).
Looper version: 1.2.0-dev
Command: inspect
Project 'bedstat' (/Users/mstolarczyk/Desktop/testing/bedstat/test_bedstat.yaml)
4 samples: ews1, ews4, ews407, ews9
Sections: pep_version, sample_table, name, sample_modifiers, looper
```

**Comment by nsheff** [comment]
indeed you are correct. my mistake.
