### ISSUE TITLE
relative pipeline interface paths should be relative to the PEP

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#268]
Right now, if you use a relative pipeline interface path, such as is used in the [hello_looper repository](https://github.com/pepkit/hello_looper), looper is assuming the piface will be relative to the current working directory, which is wrong. it should be considered relative to the PEP that specifies the piface.

**Comment by nsheff** [comment]
This is not solved in my hands with the current release of looper -- at least for project pipelines. is it possible you solved it for sample pipelines but not project pipeline interfaces?

**Comment by stolarczyk** [comment]
I think it was fixed for both because they were one file at the time, but then we split sample and project pipeline interfaces..

**Comment by nsheff** [comment]
makes sense. thanks.
