### ISSUE TITLE
PEPENV compute partition hard-coded?

### ISSUE THREAD

**Issue by jpsmith5** [pepkit/looper#27]
Is there a reason the computing partition variable is hard-coded into looper.py and the submission_manager.py?  Can we have looper simply access any/all variables in the PEPENV file instead? I've noticed that if a user wants to include additional environmental level variables in the user's PEPENV yaml file, looper does not see these additional variables.

**Comment by nsheff** [comment]
yeah, it's all we've ever used -- but I like the flexibility that a user could put whatever they need to in there. we don't know what future resource managers will require, or other environments -- for example, the current one, where a user needs to specify an account.

**Comment by vreuter** [comment]
Yeah that makes sense. And this seems like a spot where bad input would tend to trigger fast failure, so the danger incurred by the flexibility feels well worth it.

**Comment by nsheff** [comment]
fixed in https://github.com/pepkit/looper/commit/35f17d14e441b70ab39db1aca381ef87fb1a2074
