### ISSUE TITLE
sample yaml path docs are confusing

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#273]
is the sample_yaml_path relative to something? we should write that into the docs. now we say:

"""
Looper produces a yaml file that represents the sample. By default the file is saved in submission directory in {sample.sample_name}.yaml. You can override the default by specifying a sample_yaml_path attribute in the pipeline interface:

sample_yaml_path:  {sample.sample_name}.yaml

This attribute, like the command_template, has access to any of the looper namespaces, in case you want to use them in the names of your sample yaml files.
"""

that explains how to override the default file name, but can you override the default *directory* ?

**Comment by stolarczyk** [comment]
currently the result of path template rendering is appended to `looper.output_dir`, unless it's an absolute path. It is returned as is, then.

So, yes, directory overwriting is supported. But I need to double check if env vars are expanded after template rendering.

**Comment by stolarczyk** [comment]
>  I need to double check if env vars are expanded after template rendering.

They are now. So you can do:

- `{sample.attr}_file.yaml` -- will be appened to the default directory (`looper.output_dir`)
- `$HOME/{sample.attr}_file.yaml` -- absolute, portable path
- `/home/xxx/{sample.attr}_file.yaml` -- absolute path

**Comment by nsheff** [comment]
Ok I think we just need to make clear in the docs that absolute paths are allowed, or relative paths, which are then relative to the output dir.
