### ISSUE TITLE
looper submits duplicate jobs when protocol mappings section has multiple alpha-equivalent strings mapped

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#29]
if a sample annotation file contains two different `protocol` strings that both map to the same pipeline, Looper is submitting that pipeline two times for each of the sample named by either of those two strings.

**Comment by nsheff** [comment]
short-term workaround: make sure your sample annotation file uses only a single standard protocol for each type.

**Comment by nsheff** [comment]
actually the problem is really in a protocol mappings section that tries to map multiple alpha-case-equivalent protocols to the same pipeline. because the protocol mappings section ignores case, this has the effect of mapping two pipelines to the same protocol.

solution: warn authors of a pipeline interface file if they try to use more than one representation that is ignore-case-equivalent in the protocol mappings section.

**Comment by vreuter** [comment]
Has this already been solved?

**Comment by nsheff** [comment]
No, I don't think it has been solved.

**Comment by vreuter** [comment]
A series of commits introduced into `dev` with [this PR](https://github.com/pepkit/looper/pull/137) test for lack of this behavior. I think this is all set now and shouldn't arise again since we're no longer doing a soft match on protocol.
