### ISSUE TITLE
Improving looper summarize

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#30]
Currently, summarize does a nice job producing a text table, and we have a rudimentary html report that displays figures. It's time to take this to the next level. This issue is to collect ideas, discussion, and TODO tasks for taking `looper summarize` to the next level.

## HTML report
The HTML report includes:
- [x] link to full stats spreadsheet
- [x] samples in table are links to individual sample HTML pages
- [x] individual sample pages for each sample (with thumbnails linking to main objects)
- [x] section 2: list of all objects produced, linked to individual HTML pages
- [x] individual object pages for each object (with thumbnails linking to main objects)
- [x] HTML page for each sample, which contains metadata for each sample and any stats and plots generated by that sample
- [x] links back to main parent page, etc.
- [x] stick in a canned free style sheet like from [bootswatch](https://bootswatch.com/)
- [x] sample pages should have links to their log files
- [x] section 3: any project-level summary plots produced by summarizers
- [x] display a colored status showing the run's flag file.
- [x] a 'Status' page that just shows the flag summary for each sample. (graphical equivalent of looper check)
- [x] add link to: profile.tsv, commands.sh, anything else that's auto-produced?
- [x] pipeline interface needs to have a way to tell the summarizer what it produces

## summarizers

summarize needs to be able to run `summarizers`, which will be provided by the pipeline. these summarizers can be anything and will be specified in the pipeline interface. we just need to establish a standard interface. these are scripts that take the whole collection and produce some extra plot, like a project-wide comparison of some statistic that was reported.

The summarize interface could be that it is simply run with a single argument: the path to the parent output directory. the script (to be distributed with the pipeline) would then use this information, along with what the pipeline author already knows about where stuff is kept, to get access to any individual files produced by the pipeline.

**Comment by nsheff** [comment]
input welcome from @jpsmith5, @afrendeiro, @vreuter

**Comment by jpsmith5** [comment]
**HTML report:**

I was thinking about this as well.  One advantage to some other "pretty" html reports I've looked at is that the report is completely self contained via base64 encoding.  That way, all plots/tables/etc can be fully embedded with the path to the individual files being incidental if desired.  The same process goes for embedding javascript and css into a single html file.  This then enables auto adjusting of images for browser size and different monitors etc., as well as generating table of contents to subsections of interest.  Be interested if others think this has utility.  One issue to the embedding of images up front is that we need to produce pngs or svgs in addition to pdfs for the base64 encoding to work from my reading of the process.

Is there interest in plotting a flowchart of the pipeline commands (a la pulling from the commands.sh file showing sequential pipeline commands)?  And/or tying this into the time for each step from _profile.tsv?  Potentially use something like [DiagrammeR](http://rich-iannone.github.io/DiagrammeR/).

**Comment by nsheff** [comment]
Another thought: even better, the summarizers single argument should be the `project_config.yaml` file. Then these files could use either `pep` or `peppy` and do whatever they need.

**Comment by nsheff** [comment]
> That way, all plots/tables/etc can be fully embedded with the path to the individual files being incidental if desired

How is this better than just making an output folder that has all images relative? You can still do the adjustments, etc. you describe, couldn't you? I guess it makes it a little more portable?

> Is there interest in plotting a flowchart of the pipeline commands (a la pulling from the commands.sh file showing sequential pipeline commands)? And/or tying this into the time for each step from _profile.tsv? Potentially use something like DiagrammeR.

Definitely, a result of the information from the `_profile` file would be great. since looper pipelines are purely sequential I'm not sure `diagrammeR` is useful, but they don't have any real examples in their docs that I could see at first glance, so not sure.

**Comment by jpsmith5** [comment]
Yes, little more portable is the only true gain.  And it does present a negative in that large image files make the html file that much larger I suppose.

A partially made example
![partial example](https://user-images.githubusercontent.com/29147871/40847893-9353f7be-658b-11e8-867f-e49785077869.png)

**Comment by jpsmith5** [comment]
Basically, plot shows Primary Command structure with the specific commands to that run.

Then could add tooltip mouse hover style, or label to side of connecting lines that show: time to run that command and/or relevant information to primary command such as software version info

**Comment by jpsmith5** [comment]
Full path version:

![pipeline command structure](https://user-images.githubusercontent.com/29147871/40855717-4efa8656-65a3-11e8-8adf-a389e7bf163c.png)

**Comment by nsheff** [comment]
it's tough to see those plots. at first glance...I think a more useful plot would be just a barplot showing the total processing time taken and and how it breaks down by command (maybe for the top X% of the time or something).

**Comment by nsheff** [comment]
But I think at this point we should prioritize, because I'd like to get a working example of this by next week, and the points in the checkbox above seem to be the most critical to have at least something. Once we have a minimal structure then I think we move forward to more advanced things like the flowchart diagram.

**Comment by jpsmith5** [comment]
So, something more like this?:

![times](https://user-images.githubusercontent.com/29147871/40859885-4358f9c8-65b1-11e8-8cc3-66c2d598c69d.png)

**Comment by nsheff** [comment]
that is excellent.

**Comment by afrendeiro** [comment]
In my view the most immediately useful would be an embedded stats spreadsheet where clicking in a sample row would open a new page (or maybe sliding down from the spreadsheet row) with sample specific summary which would include any figures for the sample.

Thinking more ahead (since the thread seems future-looking), looper could run in the background, routinely check the flags and stats files of samples and report to an html interface in real-time.
In a HPC environment, if we further could track which job is connected to which sample, we could even potentially extended the interface to send commands to operate on sample's jobs (e.g. pause, cancel, restart, etc). I believe there was some initial experiment on this by me using [Flask](http://flask.pocoo.org/) in some branch at some point, but obviously the time was not right for that then.

**Comment by nsheff** [comment]
>  Building on Nathan's initial suggestions, in my view the most immediately useful would be an embedded stats spreadsheet where clicking in a sample row would open a new page (or maybe sliding down from the spreadsheet row) with sample specific summary which would include any figures for the sample.

agreed. we are almost there... @jpsmith5 will have a PR for your to review soon

> Thinking more ahead (since the thread seems future-looking), looper could run in the background, routinely check the flags and stats files of samples and report to an html interface in real-time.
In a HPC environment, if we further could track which job is connected to which sample, we could even potentially extended the interface to send commands to operate on sample's jobs (e.g. pause, cancel, restart, etc). I believe there was some initial experiment on this by me using Flask in some branch at some point, but obviously the time was not right for that then.

Yeah, this is related to the "lurker" idea I wanted to implement a few years ago. I think there are some complications with it but good to keep in mind.

**Comment by nsheff** [comment]
@afrendeiro can you please have a look at #34

**Comment by nsheff** [comment]
Closing this issue since we completed all these, and have new issues for later versions of summarize.
