### ISSUE TITLE
plugins defaults for file names

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/looper#306]
Currently our plugins produce files with the following default names:
- `looper.write_sample_yaml`: {sample.name}.yaml
- `looper.write_submission_yaml`: {sample.name}_submission.yaml

should we change the first one to {sample.name}_sample.yaml to make the naming convention consistent?

**Comment by nsheff** [comment]
I actually don't mind it the way it is, since that's the old behavior.

what's the CWL plugin's version? {sample.name}_cwl.yaml ?

**Comment by stolarczyk** [comment]
> what's the CWL plugin's version? {sample.name}_cwl.yaml ?

yes

**Comment by nsheff** [comment]
I think I'd leave it, on the grounds of backwards compatibility. but if you want to change it I guess I'm ok with it.

**Comment by stolarczyk** [comment]
following the conclusions in #307, I'll change the defaults to make names consistent:

- looper.write_sample_yaml: {sample.name}_sample.yaml
- looper.write_sample_yaml_cwl: {sample.name}_sample_cwl.yaml
- looper.write_submission_yaml: {sample.name}_submission.yaml

**Comment by nsheff** [comment]
what about the project-included variant of the basic function? should that be a parameter instead of a separate function? if separate, it should have a separate output.

**Comment by stolarczyk** [comment]
Oh yeah I forgot about this one. It's a separate plugin now. So it should have a separate output and separate key to parametrize it.
