### ISSUE TITLE
remove `pipeline. sample_yaml_path` key?

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/looper#307]
before we implemented the pre-submission hooks system the sample yaml path could be changed with `pipeline. sample_yaml_path` key. Now we want to take advantage of the new `pipeline.var_templates` section. Therefore, I've decided to make the `looper.write_sample_yaml` plugin parameterizable with `pipeline.var_templates.sample_yaml_path` but kept the old way (with lower priority) for backwards compatibility. But this release will make big changes in the way we save sample yamls etc, so maybe we should completely switch to the new system?

_Originally posted by @stolarczyk in https://github.com/pepkit/looper/pull/292#issuecomment-700898909_

**Comment by nsheff** [comment]
by completely switch, the only thing that means is drop backwards compatibility?

**Comment by nsheff** [comment]
For things like this that are actually being used I'm generally in favor of keeping backwards compatibility, at least for awhile. it can be deprecated and warned. but you've already implemented it -- what's the advantage of dropping backwards compatibility? it just has potential to frustrate users.

**Comment by stolarczyk** [comment]
>  what's the advantage of dropping backwards compatibility?

making things simpler. 

I thought we might eliminate the old way since backwards compatibility is already broken since the sample yaml creation will need to be explicitly defined as a pre-submission hook. So current users will need to edit piface anyway. But, I don't have strong feelings about keeping it until next major release..

**Comment by nsheff** [comment]
ok good point. that's fine with me in that case since it's already broken.
