### ISSUE TITLE
plugin parameters should differ

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#308]
Along the lines of #306... right now the built-in plugins all use the same parameter name, but that makes it so you can't run more than one of them. 

They need separate parameterization variables.

**Comment by stolarczyk** [comment]
The do have separate ones

**Comment by stolarczyk** [comment]
We need to adjust the documentation though. I'll do it later on.

**Comment by nsheff** [comment]
ah, ok! it was a docs issue then. ok yeah I'm messing with that now, don't touch :).
