### ISSUE TITLE
summarizer dependencies

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#31]
what do we do about summarizers with dependencies?

for example, we have a summarizer that requires `pepr`. where does that dep go?  docs need to indicate these things.

it also does not fit with our current containerization strategy.

**Comment by nsheff** [comment]
This issue has been re-raised by @armonazizi in https://github.com/pepkit/looper/issues/48#issuecomment-443273571

We need to think of a way for looper to use the PEPENV settings to run `summarize`, not just `run` as it does now; and then we also need to provide in the containers everything needed for `summarize`.

**Comment by stolarczyk** [comment]
will be solved by `looper collate` in #238
