### ISSUE TITLE
redundant code in CWL plugin?

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/looper#310]
@nsheff, it looks like this entire code block is not used in the plugin. What was the intent here?
https://github.com/pepkit/looper/blob/5909ff15c1924ceefcca4987f2eb956a513bb364/looper/conductor.py#L124-L135
It all leads to `s`, which is not used downstream.

**Comment by stolarczyk** [comment]
I think I get it, did you mean to replace `namespaces["pipeline"]["input_schema"]` in the for loop and iterate over `s` instead?

**Comment by nsheff** [comment]
I think you're looking at an old commit.

**Comment by stolarczyk** [comment]
noo.. I'm I think looking at the current state of the `cwl-files` branch

**Comment by nsheff** [comment]
it was old in my mind :). does this look better?

**Comment by nsheff** [comment]
I apparently hadn't finished my last test, which I just tried now.
