### ISSUE TITLE
hello world page missing?

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#311]
I'm running NoScript in Firefox on OSX, so may be specific to my setup, but I see nothing on the ["hello world" page](http://looper.databio.org/en/latest/hello-world/) of the docs

**Comment by vreuter** [comment]
It's visible on `dev` docs but not `latest`.

**Comment by nsheff** [comment]
Sorry for missing this!

There was some readthedocs error with all our jupyter docs builds. Just re-building it solved the issue. So, it's back up now.
