### ISSUE TITLE
docs version

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#312]
Any chance the "latest" docs could be updated? I was fumbling around trying to pass pypiper args to a pipeline, and realized things had changed to `--pipeline-args` and then to `--command-extra`, per https://github.com/pepkit/looper/issues/257

It seems like some of the relevant changes are now in the PyPI version and in `master`, but that the `latest` docs don't include this stuff (but the `dev` docs do), but maybe I'm wrong. If this is the case, could the docs be synced?

**Comment by stolarczyk** [comment]
`--command-extra` docs are available here: http://looper.databio.org/en/latest/parameterizing-pipelines/

but that might be a result of the docs re-build @nsheff mentioned in #311

**Comment by nsheff** [comment]
Sorry, we had some docs building issues, which were related to a breaking change introduced in the jupyter nbconvert... I fixed it in 

https://github.com/databio/mkdocs-databio/commit/19ea487c876ebc3cf4bccd2f134042280e07eded

but I needed to rebuild all the docs which I hadn't done. This morning I rebuilt the looper docs.

**Comment by nsheff** [comment]
I'll close this issue but reopen or create new issues @vreuter if you encounter any more issues with the docs!

**Comment by vreuter** [comment]
Cool, thanks!

>
