### ISSUE TITLE
Looper as a plugin for Airflow

### ISSUE THREAD

**Issue by AllamSudhakara** [pepkit/looper#313]
Hi,

I am newbie where I would need to formulate a solution for bigQuery processing using Airflow and Looper. I do not know the full details yet but this project would require loading target tables by repeatedly looping through different pipelines for fetching data from different sources. I do see that it is possible to add Python plugins to airflow and probably modify UI for making it an integrated platform. Could you please let me know if it could be done where Looper becomes a plugin for Airflow?

**Comment by donaldcampbelljr** [comment]
Given that this issue is over 3 years old and without any activity, I will go ahead and close it. Please feel free to re-open if necessary.
