### ISSUE TITLE
Error with peppy

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#316]
Using dev version of looper and running refgenie builds, I get:

ImportError: cannot import name 'make_abs_via_cfg' from 'peppy.utils'

does it rely on a version of peppy that is not specified?

**Comment by nsheff** [comment]
I think just a reminder to update peppy requirement at release.

**Comment by vreuter** [comment]
@nsheff do you have an example of a `refgenie` build command which triggered this error? I'd like to at least test locally and perhaps also add a test that would fail now but then succeed with a version bump of the `peppy` dependency.
