### ISSUE TITLE
clarify docs on variable namespaces

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#323]
http://looper.databio.org/en/latest/variable-namespaces/

in the looper namespace:

- is `sample_output_folder -- a sample-specific output folder (results_subdir/sample.sample_name)` provided for project pipelines or only sample pipelines?
- several things under 'other' are actually paths.

**Comment by donaldcampbelljr** [comment]
-Clarified the docs to show that the sample_output_folder will use either the sample or project name.
-Also removed mention of the pipeline_config as it seems that it now uses pep_config.
-Moved variables that are paths to be under the paths sections.

See commit: https://github.com/pepkit/looper/commit/b0e5918c49c4564a2eb637ae4c8d2f9fbfd35c72
