### ISSUE TITLE
Pipestat warnings on dev are a bit verbose

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#331]
Right now I get this:

```
## [1 of 2] sample: sample1; pipeline: demo
Pipestat configuration incomplete for Sample 'sample1'; caught exception: AttributeError("'pipestat_config' attribute is missing")
Could not determine pipestat namespace. Caught exception: AttributeError("'pipestat_config' attribute is missing")
```

These will show up for any non-pipestat-compatible pipeline. These are confusing to a user. Are they necessary? Since pipestat-compatibility is optional, I would recommend no exception or Error messages printed. At most it could be maybe "This pipeline is not pipestat compatible. Add a 'pipestat_config' attribute to your PEP if you want to use pipestat" -- But even that is probably overkill... ?

Perhaps an error is warranted if the pipeline *is* pipestat-compatible, but there's something missing?

I think maybe a good way to approach this would be a check in the looper output, like

```
Checking for pipestat compatible: Pipeline is compatible with pipestat
```

Or something like that. I think we shouldn't show this for every sample, but rather just once per pipeline.

**Comment by nsheff** [comment]
@stolarczyk Do you have any comment on this?

**Comment by donaldcampbelljr** [comment]
Right now, this is logged to the terminal as:
`Pipestat compatible: False`

And it appears to be showing up once per pipeline. 

Therefore, I believe this issue has been solved.
