### ISSUE TITLE
Looper should speak pephub

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#341]
What if you could `looper run pephub://databio/project` ? 

In other words, instead of passing sample metadata via a file, you pass it via registry path. Looper needs to learn to speak the PEPhub API.

**Comment by Khoroshevskyi** [comment]
Issue #342 blocks this one. Looper config should be decoupled from PEP

**Comment by nsheff** [comment]
@Khoroshevskyi can you add a section in the docs on how to do this? Actually I think it would be great to:

1. [ ] include the example config in the docs to show how to set it up.
2. [ ] add an example to `hello_looper` to show how to run it?
3. [ ] update the `looper init` functionality to be able to also populate it with pifaces
