### ISSUE TITLE
Local variable used before defined in Checker

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#355]
https://github.com/pepkit/looper/blob/dev/looper/looper.py#L123

@nsheff do you know what should be going on here? I'm guessing maybe this isn't hit yet since it requires use of "new" `Checker` that's using `pipestat`?

**Comment by donaldcampbelljr** [comment]
The new `Checker` is working fine to generate a table if looper is configured to use pipestat and it hould not be able to access the new `Checker` if pipestat is not configured.
```
looper check ./hello_looper-master/project/project_config_pipestat_example.yaml
Looper version: 1.4.0-dev

     'count_lines' pipeline status summary     
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   Status   ┃     Jobs count/total jobs      ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│   failed   │              1/5               │
└────────────┴────────────────────────────────┘
```
I believe this is not an issue?
