### ISSUE TITLE
Enum type for entity level type/name

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#360]
We have the notion of "_project_"-level and "_sample_"-level entities and operations. Right now, some of the behavioral and messaging differences for these concepts are controlled through passing the strings `"sample"` or `"project"` to toggle between the two. This should be better formalized at the type level with an enum type to disambiguate, which would likely allow better editor hints and type annotation / checking.

**Comment by donaldcampbelljr** [comment]
This could be tackled along with the pipestat refactoring.

**Comment by donaldcampbelljr** [comment]
Ok, I added this enum and did some refactoring for the upcoming 1.8.0 release.
