### ISSUE TITLE
handle keyboard interrupts

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#37]
when proceeding under local compute mode, looper should more gracefully handle keyboard interrupts, passing them on the to command it was running and allowing that command a few seconds to shut itself down before terminating.

**Comment by donaldcampbelljr** [comment]
A quick internet search suggests that we could wrap any major loops in Try Excepts where the exception to handle is `KeyboardInterrupt`:

```
try:
  looping_over_looper_samples()
except KeyboardInterrupt:
  Clean up and Exit code
```

**Comment by donaldcampbelljr** [comment]
The above suggestion is not quite what is desired. We want to have looper send a weak kill signal to the subprocess that it has spawned (e.g. the pipeline). PyPiper actually currently has a way of sending a weak kill signal (SIGTERM) and waiting a few seconds before sending the SIGKILL to the pipeline.

**Comment by donaldcampbelljr** [comment]
Ok, I've lifted some of the code from PyPiper and now have this working in Looper with simple testing.

**Comment by nsheff** [comment]
excellent!
