### ISSUE TITLE
make `looper_args` more flexible

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#38]
Currently, a pipeline author can set `looper_args: True` in the `pipeline_interface`, and then `looper` will pass 4 arguments:
- `-M` (memory)
- `-O` (output folder)
- `-C`(config)
- `-P`(processors)

There's no way to do a subset. Right now I want a pipeline  that will take `-O` only. I have no way to access these.

We can maybe think of a more generic system to use project-level attributes in commands so that it could be done manually.

https://github.com/pepkit/looper/blob/b36c178ea31168fb3c67c90805b424652f2e7018/looper/utils.py#L17-L69

**Comment by nsheff** [comment]
What did you decide to do for the `looper args` stuff?

I think this is not solved... we haven't really decided what to do here.

did you eliminate 'looper args' as a possibility? How do you get  at memory, for instance? 

One way could be a  compute dict, which you would refer to with for example: `{compute.memory}`
kind of like the `project` and `sample` ones.

**Comment by stolarczyk** [comment]
you're right, I'm not sure why I closed it. This might have misled me:
> We can maybe think of a more generic system to use project-level attributes in commands so that it could be done manually

The dict way of accessing these arguments sounds good, but I have two reservations about:

- name: since output_folder and config are there, compute is not accurate (?)
- activation: do we still need `looper_args` entry in the config? Maybe these can be always available and added on user request in the `command_template`?

**Comment by nsheff** [comment]
> since output_folder and config are there, compute is not accurate

I don't understand

> activation: do we still need looper_args entry in the config? Maybe these can be always available and added on user request in the command_template?

Right -- that's what I was asking about regarding the `looper args` stuff... So it seems right now it's still needed. but potentially it could be removed and then you would add them like

```
compute_template: >
  ...
  -m { compute.memory }
  - n { compute.jobname }
```
etc.

The `looper args` concept is really a connection between pypiper and looper. So the alternative is essentially just that we would document all the available things that looper makes possible automatically in the `compute` object. Or, maybe it's called the `looper` object.

**Comment by stolarczyk** [comment]
> I don't understand

I don't associate output folder path and config file path with compute-related settings, that's why the compute namespace does not feel right for these. But maybe it's just me.

**Comment by nsheff** [comment]
Oh now I see. maybe a `looper` namespace makes more sense?

**Comment by nsheff** [comment]
cool!

**Comment by nsheff** [comment]
So this is the way you'd do this now: 

```
      -O {looper.output_folder}
      {% if looper.job_name is defined %} -J {looper.job_name} {% endif %}
      {% if looper.cores is defined %} -P {looper.cores} {% endif %}
      {% if looper.mem is defined %} -M {looper.mem} {% endif %}
```

Can you make a note to keep track of all of the looper-provided parameters? we'll need to add this to the docs

- `looper.output_folder` - ???
- `looper.job_name` - automatically created by appending the sample name to the pipeline name
- `looper.mem` - taken from the compute resource determination
- `looper.cores` - taken from the compute resource determination

**Comment by nsheff** [comment]
Here are the original 'looper args':

looper: config, output-parent, mem, cores

so you've added job_name, and we're missing config.

Also, output parent is not the same as output_folder, right? so these are actually separate things available in the looper namespace

**Comment by nsheff** [comment]
I'm trying to wrap my head around the different things that are all coming together here. It's pretty interesting. Here are sources of attributes:


## `project` namespace

Any top-level attributes listed in the PEP, like `project.name` or `project.genome`

## `sample` namespace

Any sample attributes populated by `peppy`.

## looper subsection of PEP

Attributes originally in `metadadata` were used by looper to add arguments to pipeline commands. Where do these go?

```
looper:
  output_folder: path/to/parent/output
```

Is this translated into: `looper.output_parent`  ? or `looper.output_folder` ?

It's a bit confusing because some of these are used by looper internally (like `submission_subdir`). I propose we just make available any attributes listed in the `looper` section of the PEP project config file.

## automatic attributes in the `looper` namespace

In addition to making user-provided attributes available, looper creates a few of its own:

- `looper.output_folder` - automatically created as `{looper.output_parent}/{sample.sample_name}` -- potential name clash here we should think about.
- `looper.config` - looper automatically creates this in the original version.
- `looper.job_name` - automatically created by appending the sample name to the pipeline name

Another complexity is that some of these are used internally by looper, others originally could be added to commands. I propose again we follow the pattern of just making everything available in the command templates.

## Attributes made available by the `divvy` configuration,  and by the resources management system:

Are these all 1 namespace or separate? 

- `looper.XYZ` -- any other attributes made available in the `divvy` config for the selected compute package, 
- `looper.XYZ` -- any other attributes made available in the `looper.compute` section of the PEP
- `looper.XYZ` -- any other attributes made available in the `resources` section of the pipeline interface (we usually use `looper.mem` and `looper.cores`, and `looper.time`)

The complexity here is that the compute settings are derived from several sources. Again we should make all of these available, but in what namespaces? All into `looper.X`?

**Comment by nsheff** [comment]
this so far has ignored the complexity required for cascading priority settings, raised in https://github.com/pepkit/looper/issues/185
