### ISSUE TITLE
looper summarize, report, table

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/looper#390]
In 2020, `looper summarize` was split into `report` and `table` functions: https://github.com/pepkit/looper/pull/255

`looper report` is intended to create a static html report. `looper table` provides "Project/Sample statistics and table output generator".

Currently (in Looper 1.5.0), there are two Reporter classes (`Reporter` and `ReporterOld`) and two Tabulator classes (`Tabulator` and `TabulatorOld`). It appears that with the release of Looper 1.4.0, `looper report` and `table` were to only be used when pipestat is configured.

However, `looper` will currently still use the `ReporterOld` and `TabulatorOld` classes if pipestat is not configured.

We've also recently moved the report generation to `pipestat.summarize` such that `looper report` (when configured to use pipestat) will call `Reporter` class which uses pipestat.sumamrize to generate the html report. However, `looper table` and Tabulator Class are still completely contained within looper.

**Some questions:**
- Do we still want `looper table` and should we also move the creating of the stats table generation to pipestat and have looper table call something like `pipestat.table`?
- I noticed looper will only use the newer Reporter and Tabulator classes if: 1. pipestat configuration is given in the config file AND 2. we use `--project` as an argument in the CLI. Otherwise, looper uses the older classes. Is there a reason for requiring these to run at the project level? 

**Thoughts on path forward:**
- [x] ensure `looper table` works with the current versions of pipestat v0.5.0 (currently it appears to be broken).
  - [x] move stat table generation to pipestat?
- [x] remove TabulatorOld, ReporterOld, CheckerOld give the user a warning if they attempt to use `report` or `table` without configuring pipestat.
- [x] remove html report generation code from looper completely (its still present because ReporterOld is still using it).
- [x] write tests to confirm looper can be configured to use pipestat and use the above functions without issue.

**Comment by nsheff** [comment]
Yes. I think you are thinking in exactly the right way.
