### ISSUE TITLE
calling looper from CLI without arguments fails

### ISSUE THREAD

**Issue by afrendeiro** [pepkit/looper#4]
Since the 'subproject' option in argparser is only added the command-specific arguments (https://github.com/pepkit/looper/blob/master/looper/looper.py#L169), there is an error when looper is called without any argument because main() assumes there is an 'subproject' attribute in args (https://github.com/pepkit/looper/blob/master/looper/looper.py#L802).

**Comment by vreuter** [comment]
I'll include a fix for this on the `use-pep` branch that will have looper importing from `pep`

**Comment by vreuter** [comment]
I think this actually may be due to the presence of subparsers...are you talking about running simply `looper` with no arguments, or `looper <prog>` with no additional arguments?

For me, just `looper` produces an error from `argparse` as I'd expect, but `main()` is hitting an `AttributeError` where you mention, then that's something different.

**Comment by afrendeiro** [comment]
I meant just `looper` with no arguments.
This should just display the help listing the various subcommands, right?

**Comment by vreuter** [comment]
I think normally you have to do something like `-H` or `--help` to get that. We could probably make just `looper` do the help--that doesn't seem like it'd be impossible--but I think that's different than ordinary command-line tools like `cut`/`curl`/`wget`

**Comment by nsheff** [comment]
When I run looper plain, I get:
```
looper
usage: looper [-h] [-V] [--logfile LOGFILE] [--verbosity {0,1,2,3,4}] [--dbg]
              {run,summarize,destroy,check,clean} ...
looper: error: too few arguments
```
@afrendeiro are you looking for something else?

**Comment by afrendeiro** [comment]
I somehow can't reproduce this now with either of the released versions. I think it might have been specific to a something in progress. Closing.
