### ISSUE TITLE
Relative directory for pipeline interfaces.

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#406]
In earlier versions of the looper, the pipeline interface was defined in the PEP (as sample attributes). Relative paths were considered relative to the PEP sample table, I guess.

But 2 things have changed:

1. In the dev version of looper that introduces looper config, the pipeline interface is defined in the looper config file.
2. now that looper can get PEPs from PEPhub, what should a relative path be relative *to* ? In the current implementation, this has been made relative to the current working directory.

This is a problem, because it means I can't just change from a local to a PEPhub PEP, leaving the rest of the file the same. I would also have to change the pipeline interface relative paths.

Shouldn't the pipeline interfaces (and other looper settings) be made relative to the looper config file, now that that's where they're specified (instead of the PEP or sample table)?

**Comment by nsheff** [comment]
Related to #344

**Comment by donaldcampbelljr** [comment]
Closed via https://github.com/pepkit/looper/pull/400
