### ISSUE TITLE
Proposed revision to lump functionality

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#415]
I propose we revise the `lump` arguments to these:

- `--lump-n <n>`: (currently `lumpn`) puts *n* samples together
- `--lump-s <size>`: (currently `lump`) puts together samples until they reach `size` in total input file size
- `--lump-j <jobs>`: (not currently implemented) divides samples into *jobs* different jobs

This adds the `lump-j` functionality (which should be really easy to implement, just piggyback on the `lump-n` functionality). And then, it streamlines the terminology; I'm always confused at whether I should use `lump` or `lumpn`.

Thoughts:
- this would be a (minor) change to the UI
- is the new lump-j useful enough? Only if implementing it is very simple (which it should be)
- are the names intuitive? `-s`, `-j`, and `-n`? I think `-s` could mean either size or sample. But I can't think of anything better.

**Comment by donaldcampbelljr** [comment]
Better to think of it as starting with number of jobs and then having looper distribute samples across jobs (processors).
