### ISSUE TITLE
pytest passes locally but fails on github: hypothesis.errors.FailedHealthCheck

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/looper#416]
looper is failing on dev branch with a new error during pytest on github. However, the tests are all passing locally.
Appears to be related to hypothesis module.

```
=================================== FAILURES ===================================
______ NaturalRangeFromStringTests.test_just_delimiter__does_not_parse[-] ______

self = <tests.test_natural_range.NaturalRangeFromStringTests object at 0x7f4ea9d2b850>
legit_delim = '-'

    @given(upper_bound=st.integers())
>   def test_just_delimiter__does_not_parse(self, legit_delim, upper_bound):
E   hypothesis.errors.FailedHealthCheck: The method NaturalRangeFromStringTests.test_just_delimiter__does_not_parse was called from multiple different executors. This may lead to flaky tests and nonreproducible errors when replaying from database.
E   See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.differing_executors to the suppress_health_check settings for this test.

tests/test_natural_range.py:65: FailedHealthCheck
=========================== short test summary info ============================
FAILED tests/test_natural_range.py::NaturalRangeFromStringTests::test_just_delimiter__does_not_parse[-] - hypothesis.errors.FailedHealthCheck: The method NaturalRangeFromStringTests.test_just_delimiter__does_not_parse was called from multiple different executors. This may lead to flaky tests and nonreproducible errors when replaying from database.
See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.differing_executors to the suppress_health_check settings for this test.
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by donaldcampbelljr** [comment]
Ok, I am able to reproduce this error locally (using python 3.8) if I upgrade Hypothesis from v4.38.0 to v6.87.1.

**Comment by donaldcampbelljr** [comment]
`v6.80.0` passes but with `v6.84.0` I begin to see failures. Will investigate Hypothesis changelog around these releases to see if its obvious why this would cause flaky test failures in python 3.8.

**Comment by donaldcampbelljr** [comment]
From release notes:


> 6.83.2 - 2023-09-04[¶](https://hypothesis.readthedocs.io/en/latest/changes.html#v6-83-2)
> Add a health check that detects if the same test is executed several times by [different executors](https://hypothesis.readthedocs.io/en/latest/details.html#custom-function-execution).

**Comment by nsheff** [comment]
might just need to update the `requirements-test` to set a new minimum version of hypothesis.

or, maybe it makes sense to just eliminate hypothesis-based tests. personally, I don't know what it does and I prefer keeping the tests very simple.

**Comment by vreuter** [comment]
`hypothesis` is the most popular (AFAIK) package for [property-based testing](https://en.wikipedia.org/wiki/Software_testing#Property_testing) in Python. Some typical benefits are the automatic (rather than manual) construction of (often (configurably) many) test cases (and as corollary, discovery of edge cases with unexpected behavior), and the "shrinking" of test cases to the "smallest" possible failure case, with the idea that it makes a problem easier to understand a patch simpler to discover.

It sounds like this behavior was deemed to generate too many false positives and [was removed](https://hypothesis.readthedocs.io/en/latest/changes.html#v6-84-3) as [discussed here](https://github.com/HypothesisWorks/hypothesis/issues/3733).

**Comment by donaldcampbelljr** [comment]
I installed a new version of hypothesis (v6.92.0) and am still getting failures for `tests/test_natural_range.py` (hypothesis.errors.FailedHealthCheck).

Perhaps this is not a false positive?

**Comment by vreuter** [comment]
Good catch @donaldcampbelljr I'd not noticed that this wasn't a `parametrize`d test. I think the change in `hypothesis` only suppresses it by default in that case, so in this case of the failing test, I guess it's not turned off just by bumping the version.
