### ISSUE TITLE
looper is forcing the pipeline file to be executable, even if the command template doesn't execute it

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/looper#420]
looper is forcing the pipeline file to be executable, even if the command template doesn't execute it (I was using 'python script.py').

**Comment by donaldcampbelljr** [comment]
Currently, in Looper's conductor.py, we check if the commands in the pl_iface is executable:
https://github.com/pepkit/looper/blob/145c0d6796d45e45a4ec133beed5be30e1860553/looper/conductor.py#L724-L725

This was implemented as a potential solution to this:
https://github.com/pepkit/looper/issues/195

Specifically, it is using:
`is_command_callable` from `ubiquerg`

https://github.com/pepkit/ubiquerg/blob/bbca867a7c3581bad51723977db3791d999d8591/ubiquerg/system.py#L11-L30

**Comment by nsheff** [comment]
This is totally unrelated to #195, actually. That's about *the commands in a pipeline*.

The problem is that this is referring to *the pipeline script itself*. These are two completely different things.

**Comment by donaldcampbelljr** [comment]
The original changes are now reverted.
