### ISSUE TITLE
Add tab completion to Looper

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/looper#422]
looper couldn't tab-complete

**Comment by donaldcampbelljr** [comment]
**Potential solutions:**
use argcomplete
https://kislyuk.github.io/argcomplete/
https://stackoverflow.com/questions/14597466/custom-tab-completion-in-python-argparse/15245680

**Comment by nsheff** [comment]
Here's how I did it in the past:

- markmeld: https://github.com/databio/markmeld/blob/master/markmeld/autocomplete/autocomplete.bash
- bulker: https://github.com/databio/bulker/blob/master/bulker/autocomplete/autocomplete.bash

these are bash functions. they rely on an autocomplete CLI parameter. It's implemented here:

https://github.com/databio/markmeld/blob/a5736131dd8f531f0f34505c698dcc36e2cafb03/markmeld/cli.py#L145-L150
