### ISSUE TITLE
Use registry_path checker from pephubclient

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/looper#426]
I added registry path checker to pephubclient, so now we should use this function from pephubclient.
How to use it:
```
from pephubclient.helpers import is_registry_path
is_registry_path(sample_pep)
```

**Comment by nsheff** [comment]
Sounds like that function belongs in ubiquerg.

There's already `parse_registry_path` there: https://github.com/pepkit/ubiquerg/blob/bbca867a7c3581bad51723977db3791d999d8591/ubiquerg/paths.py#L21

as long as there are no dependencies
