### ISSUE TITLE
Schema validation error should provide more details.

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/looper#427]
Currently if a schema fails Eido validation it simply outputs to terminal:

`Short-circuiting due to validation error: Validation failed`

https://github.com/pepkit/looper/blob/b032668b3bb7440e38bb8c95933da08de49e54a5/looper/looper.py#L433-L446

Proposed solution:
-add a bit more info to the error message from the error, e.g.:
`e.errors_by_type`

**Comment by nsheff** [comment]
Related to: https://github.com/pepkit/eido/issues/48
