### ISSUE TITLE
Documentation is unclear about the difference between `looper run` and `looper runp` commands

### ISSUE THREAD

**Issue by simeoncarstens** [pepkit/looper#436]
In https://github.com/pepkit/looper/blob/b47a568e87ecd28b7b6962ddd202a94fcafb3f9b/docs/usage.md?plain=1#L7 ff, it says
> `looper run`: Runs pipelines for each sample, for each pipeline. This will use your compute settings to build and submit scripts to your specified compute environment, or run them sequentially on your local computer.
> `looper runp`: Runs pipelines for each pipeline for project.

At least for me, it's not quite clear what the difference between these is. Both take a `looper` project configuration file, and
> runs pipelines for each pipeline for project

sounds ungrammatical at first, but then sounds like it might run "pipelines of pipelines" for a given project? If so, then that's nontrivial and would profit from more detail or a link to some other documentation explaining what "pipelines of pipelines" are.

**Comment by nsheff** [comment]
looper understands 2 types of pipeline:

1. sample-level pipelines, which will run 1 pipeline for each sample in a project
2. project-level pipelines, which will run 1 pipeline total, for the project as a whole.

`run` is for sample-level pipelines
`runp` is for project-level pipelines

we should make sure this is clear in the documentation.

**Comment by simeoncarstens** [comment]
With #437 merged, that's solved for me :slightly_smiling_face:
