### ISSUE TITLE
looper isn't working with sample_table_index

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#458]
Using a basic project with a sample table index fails, due to this line:

https://github.com/pepkit/looper/blob/1468956dde66abf5b853c80eaeaee2d411bfad64/looper/looper.py#L458

it's expecting there to be a `sample_name` column, which there is not, since I'm using `sample_table_index`.

This makes looper not fully compliant with PEP.

**Comment by donaldcampbelljr** [comment]
I believe this is a Peppy issue: https://github.com/pepkit/peppy/issues/459

**Comment by nsheff** [comment]
I don't think it's a peppy issue -- it's looper code that is referring to `sample.sample_name`

are you suggesting that peppy make available a `.sample_name` attribute to refer to wherever the index is?

**Comment by donaldcampbelljr** [comment]
> I don't think it's a peppy issue -- it's looper code that is referring to `sample.sample_name`
> 
> are you suggesting that peppy make available a `.sample_name` attribute to refer to wherever the index is?

Yes. I thought that was the original functionality.

Some digging, for reference to this issue:
https://github.com/pepkit/peppy/commit/3d5495b0241a117cdfb07ee60e15c6a3e2a516eb

**Comment by donaldcampbelljr** [comment]
Future discussion to happen in: https://github.com/pepkit/peppy/issues/459

However, will keep this open to track for Looper.

**Comment by donaldcampbelljr** [comment]
Ok, I believe this PR in Peppy (https://github.com/pepkit/peppy/pull/484) will solve this issue and the corresponding issue: https://github.com/pepkit/peppy/issues/459

- [ ] We will need to do a release of Peppy (or a pre-release) and pin that in Looper reqs.
