### ISSUE TITLE
extra pipestat message

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#461]
This extra dict is printed after a `looper run`

```
Looper finished
Samples valid for job generation: 1 of 7
Commands submitted: 0 of 7
Jobs submitted: 0
{'Pipestat compatible': True, 'Commands submitted': '0 of 7', 'Jobs submitted': 0}
```

**Comment by donaldcampbelljr** [comment]
This is happening because we add data to a `debug` dict that gets returned from the main Looper Classes (Runner, Destroyer, etc). This was implemented to aid our test suites (to check if the subprocess is succeeding from within the test).

**Comment by donaldcampbelljr** [comment]
I've cut down on the verbosity with this commit: https://github.com/pepkit/looper/pull/496/commits/541113949b726cf2b82c5c63a5d325b5aaf4a227

The info should no longer be duplicated in the terminal.
