### ISSUE TITLE
looper inspect is broken

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#462]
```
looper inspect
Looper version: 1.7.0
Command: inspect
Using looper config (.looper.yaml).
Config file does not have version key. Defaulting to 2.1.0
Config file does not have version key. Defaulting to 2.1.0
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nsheff/.local/lib/python3.11/site-packages/looper/cli_looper.py", line 760, in main
    prj.pipestat_configured_project if args.project else prj.pipestat_configured
                                       ^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'project'
```

**Comment by donaldcampbelljr** [comment]
Looking at inspect I see that there is a warning that this feature has moved to Eido and will be removed from Looper:
https://github.com/pepkit/looper/blob/8d029bf5d4308271faddfa5722f2d1c0c983988d/looper/cli_looper.py#L789-L796

It does appear that Eido has inspect functionality added in 2021 and modified as recently as June 2023:
https://github.com/pepkit/eido/blob/a2aa751d2a4db49b12bd90129cee97100291c1cd/eido/cli.py#L166-L173


#### **Question:**
Should we go ahead and remove the `inspect` command from Looper?

**Comment by nsheff** [comment]
No, those are different things to me. 

eido should inspect the PEP.

looper inspect should inspect the looper config


I guess that comment comes from before looper config was a thing.

looper inspect could include the results of the eido inspect, for the pep aspect of the config.

**Comment by donaldcampbelljr** [comment]
Should be solved with the above PR.
