### ISSUE TITLE
pipestat status flags are not working correctly

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#463]
If I run a job and it fails, it creates  a "_failed.flag", correctly.

When I try to do `looper run`, it won't run these because they have failed flags -- as expected.

So, I try `looper rerun`, and what happens is broken. it says:

```
## [2 of 7] sample: demo1; pipeline: add_to_seqcol
Initialized looper config file: /home/nsheff/code/seqcolapi/analysis/demo/looper_pipestat_config.yaml
Initialize PipestatBackend
Initialize FileBackend
> Skipping sample because rerun requested, but no failed flag found. Status: waiting
```

That's strange, because there *was* just a failed flag there, from the previous run... so I double-check and, sure enough, it has changed the flag from `failed` to waiting! 

This doesn't make any sense. It should not change the flag from failed to waiting, and then complain that "no failed flag" is found!

**Comment by donaldcampbelljr** [comment]
Ok, I found where the issue is; it is due to a fix for https://github.com/pepkit/looper/issues/169, specifically this commit: https://github.com/pepkit/looper/commit/6ccebc65f368e9d5902c3890a0c6373f9e09d169

I've added a fix here: https://github.com/pepkit/looper/pull/480
