### ISSUE TITLE
Does looper destroy also clear pipestat results?

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#469]
Say I run a sample through a pipeline that uses pipestat.  Now say I want to clear out that sample and re-run it. I call `looper destroy` and use the selector tools to choose just the one sample that needs to be re-run. I re-run it.

Are the reported stats updated? Only if looper destroy is not just deleting files, but also pipestat results, because of this bug: https://github.com/databio/pypiper/issues/209

So we should double-check -- is looper destroy correctly deleting pipestat results?

Unfortunately I wasn't able to check it because #468 

Once that issue is fixed we need to determine if destroy is working correctly. I have a hunch that it is not.

**Comment by donaldcampbelljr** [comment]
No, I confirmed this functionality does not exist. See #468

**Comment by donaldcampbelljr** [comment]
Ok, I added this functionality with the above pull request.
