### ISSUE TITLE
looper is not validating inputs correctly

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#523]
If I say that an input attribute is `required` in the input schema, then if I don't specify a value for that attribute in the CSV file, I expect looper to *not* submit the job.

But what happens is, looper still submits the job.

I am putting an example in the hello_looper repo.

**Comment by nsheff** [comment]
just add `minLength:1` to the schema.

having an attribute present is not the same thing as having something in the attribute.

**Comment by donaldcampbelljr** [comment]
- [ ] update docs to state requiring minLength in schema to have this work as the user expects

**Comment by donaldcampbelljr** [comment]
I've updated the eido and looper docs regarding `minLength`. Closing this in favor of the Eido issue.
