### ISSUE TITLE
`sizing` keyword is not working correctly

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#524]
Right now, looper is using `tangible` to determine input file size, not `sizing`.

**Comment by donaldcampbelljr** [comment]
This is happening in Eido here:
https://github.com/pepkit/eido/blob/87eead537180db57176a56e5c6e8523fdbdfd0b5/eido/inspection.py#L72-L93

It appears to be using _both_ the sizing and the tangible attributes to determine input file size by collecting all files and then calculating the input_file_size from the sum of all input files. In the hello_looper example, we use the _same_ file path for each of these, so the set of files to determine size will contain only that single supplied file path. Thus, only one file is calculated for this input_file_size.

**Comment by donaldcampbelljr** [comment]
Based on previous comment and investigation, I don't believe this was actually a bug since the example was using the same file_path for each. Closing this for now.
