### ISSUE TITLE
target links

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#55]
@jpsmith5 , is there a reason you made the link targets on the main summary page do ` target="_top"` ?

This makes it so I can't embed a summary in an `iframe`.

**Comment by jpsmith5** [comment]
Hmmm. No I think that may just be an artifact. Don't believe it's required.  I'll remove that from the process.  You're referencing the links in the main Summary.html page table to the individual sample pages correct?

**Comment by nsheff** [comment]
right. yeah, please remove it if not necessary.

**Comment by jpsmith5** [comment]
Removed with 8b281e5.
