### ISSUE TITLE
Switch to divvy for computing configuration

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#59]
The environment configuration and pepenv are useful outside looper. We should consider abstracting these into a separate package with objects related to interfacing with compute infrastructure, templating, etc.

**Comment by vreuter** [comment]
`SubmissionConductor.write_script` uses an ancillary function imported from `divvy` to do its work. This is fine, but since a conductor stores a project reference it can directly access the divvy computing configuration instance and should do so.
