### ISSUE TITLE
rename implied columns to attributes

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#60]
the project config `implied_columns` and `derived_columns` sections should instead use `implied_attributes` and `derived_attributes`

(but retain backwards compatibility)

**Comment by vreuter** [comment]
Closing for https://github.com/pepkit/peppy/issues/226

**Comment by nsheff** [comment]
hey, did you see github's new "transfer this issue" beta? :look:

**Comment by vreuter** [comment]
Nope, I see it now, though--cool!
