### ISSUE TITLE
Submission scripts as feature for docs/presentation(s)?

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#62]
I'm not sure how this compares to other job definition and submission tools, but one of the `looper` aspects I like best is the creation of the submission scripts in addition to performing the actual submission. I could see other projects going in one way or the other--wither submitting everything, _or_ writing the files to do so, but do others do both? Regardless, I think this is really cool from the standpoint of being able to easily and directly cluster settings for the submission when there's a failure, whether that's due to that constraints of the manager for a particular partition, or due to actual resource usage excess by the job. I think it'd be cool to mention this as a feature in docs and/or perhaps in one of the slides bundles for more in-depth presentations about `looper`

**Comment by nsheff** [comment]
I'm not really sure exactly what you mean here to be honest...

**Comment by vreuter** [comment]
Maybe due to the horrendous wording mishaps in the initial post :man_facepalming: 
I meant that rather than simply submitting everything and leaving no trace, looper writes the submission scripts, which makes it easy to tinker with minor settings like pipeline arguments or cluster request parameters for individual samples, say if one failed or you want to add some option after an initial run.
I still like that as a feature, but maybe it's too niche or just otherwise not worth mentioning in the docs; I don't have a strong opinion.
