### ISSUE TITLE
New command: looper set

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#64]
it would be nice if we could set `looper` project config parameters on the command line. For example,

```
looper set config.yaml "pipeline_interfaces: /path/to/piface.yaml"
```
Would update the `pipeline_interfaces` attribute in the project. This would be a convenient way for tutorials to just programatically set things up. It could prompt before overwriting existing attributes.

This could be done in conjunction with this: https://github.com/pepkit/peppy/issues/200

Related to: https://github.com/pepkit/geofetch/issues/12
It would eliminate the need for `geofetch` to implement this.

**Comment by nsheff** [comment]
@stolarczyk how do you think this integrates into the dotfile?

**Comment by nsheff** [comment]
What happened to the `looper mod` function? It looks like it was put into master on 1.2.1 according to this commit. 

But in 1.2.1 it is not functional:
```
looper --help
version: 1.2.1
usage: looper [-h] [--version] [--logfile LOGFILE] [--verbosity {0,1,2,3,4}]
              [--dbg]
              {run,rerun,runp,table,report,destroy,check,clean,inspect,init}
              ...

looper - A project job submission engine and project manager.

positional arguments:
  {run,rerun,runp,table,report,destroy,check,clean,inspect,init}
    run                 Run or submit sample jobs.
    rerun               Resubmit sample jobs with failed flags.
    runp                Run or submit project jobs.
    table               Write summary stats table for project samples.
    report              Create browsable HTML report of project results.
    destroy             Remove output files of the project.
    check               Check flag status of current runs.
    clean               Run clean scripts of already processed jobs.
    inspect             Print information about a project.
    init                Initialize looper dotfile.
```

Did get removed? I don't see it in the changelog, either as an addition or as a removal, and i

**Comment by stolarczyk** [comment]
I don't remember what exactly happened, but I think we decided no to add this command in the end and, looking at the release tags, I don't think we ever released a looper version that supported that.

**Comment by nsheff** [comment]
ok. maybe we figured out it was too complicated or something...
