### ISSUE TITLE
Pipeline interface YAML subsection sharing?

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#65]
In a project config, a subproject inherits key-value pairs from the enclosing scope (in the same file, outside the context of any subproject). Is the same true of different pipelines within the `pipelines` section of a pipeline interface file? If not, could it be / is there interest in that, or do we think that it's an insufficiently frequent desire to bother implementing it?

**Comment by vreuter** [comment]
So like in the bisulfite project, the `default` resource packages match for WGBS and RRBS. To me, the sharing feels nice but I can also see it being sort of infrequent, and relevant to things (configuration settings) that will tend to be pretty static.  I guess where it could more extensively eliminate duplication is among more directly competing pipelines, e.g. several similarly-aimed mRNA-seq pipelines, that are more likely to have more matches in terms of reasonable resource bundles based on input size.

Similarly, but in a different place, this would be nice-to-have but not high priority for pipeline parameters rather than resources (like if `rrbs.yaml` and `wgbs.yaml` pulled from a common `bisulfite.yaml`). That feels more important than resources--to me, anyway--since it concerns actual pipeline behavior and outputs rather than something like runtime and completion or not.

**Comment by nsheff** [comment]
I see.

In this case I think the increased complexity doesn't justify the little benefit we would get, since I don't see this used very often... I kind of like the idea that a pipeline interface is self-contained for a given pipeline. we would lose that if we enabled this, which will reduce portability of the pipeline. many pipelines these days live alone anyway.

**Comment by vreuter** [comment]
Sounds good
