### ISSUE TITLE
Attempt to find config from project

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#66]
I'd like to be able to point to a project root folder rather than to a config when running, e.g. `looper check`. I think a sweep through all folders for a config would be excessive, but what about automatically checking for something like `metadata/*conf*.yaml`, and having `looper` proceed to use that if there's exactly 1 match on that pattern?

**Comment by nsheff** [comment]
the problem with this is that it's so specific to our particular way of doing/naming things... would it be better to just write a wrapper around looper for yourself locally?

another approach would be a global looper config file where you could configure things like this. caravel may be something moving in that direction

**Comment by vreuter** [comment]
Yeah probably. Wanted to throw it out in case enough others do it that it'd be worth integrating, but probably not.
