### ISSUE TITLE
Dev and master are conflicted

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#69]

**Comment by vreuter** [comment]
`looper/html_reports.py`

**Comment by nsheff** [comment]
these conflicts look like relatively simple HTML errors introduced into master directly

**Comment by nsheff** [comment]
I've opened PR #70.

@aaron-gu it looks like these are your changes, would you mind reconciling these commits?

**Comment by nsheff** [comment]
Fixed in #70
