### ISSUE TITLE
summarize could add links by file type

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#72]
Right now the pipeline puts out a folder for each sample. sometimes we want files organized by type. The best way to do this is to create a relative link structure for by-type folders that link into the hierarchy of sample folders.

`looper summarize` could do this for us.

**Comment by nsheff** [comment]
I have a script that could be useful for this.

**Comment by nsheff** [comment]
https://github.com/databio/scripts/blob/master/misc/linkme.py

**Comment by donaldcampbelljr** [comment]
We will write a new function that creates these links within the filesystem.

`looper link` which will call `pipestat.link`
