### ISSUE TITLE
Dealing with summary table display with long text

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#79]
When some attributes have really long values, the looper summary table HTML report doesn't display well.

Observe:

![ss1](https://user-images.githubusercontent.com/5271009/48793302-8857ca00-ecc4-11e8-8595-6267968a2169.png)

![ss2](https://user-images.githubusercontent.com/5271009/48793303-8857ca00-ecc4-11e8-89ed-66380d1805a7.png)

2 solutions:

## DataTable elipsis:

https://datatables.net/blog/2016-02-26
https://datatables.net/plug-ins/dataRender/ellipsis

## "Show long attributes" checkbox

by default, attributes with greater than *x* characters are not shown at all (columns are not there). If checked, the table will then show these.

## put them in the (+) dialog

can we just put all the long attributes into a "+" dialog?

**Comment by vreuter** [comment]
@aaron-gu it sounds like https://github.com/pepkit/looper/pull/89/commits/ea0000ea133b6aaa68b56a9110f7cc75d7307833 addresses this but maybe you're still working on it? I'll leave open for now but feel free to close if the changes now in `dev` and headed for `master` cover it.

**Comment by aaron-gu** [comment]
Yea, I can still work on it, but the changes now are sufficient for the release.
