### ISSUE TITLE
Question: Documentation on merge tables

### ISSUE THREAD

**Issue by rcorces** [pepkit/looper#8]
I'm trying to figure out the merge table concept and have a few questions that I havent figured out from the documentation (http://looper.readthedocs.io/en/latest/advanced.html). The docs seem a bit sparse for merge tables and the github example is small and not very "real-world", at least at first glance.

1) If I have 2 different sequencing lanes set up like this:

Lane 1:
Library A
Library B
Library C

Lane 2:
Library A
Library B
Library D

My merge table should merge the sequencing files corresponding to Libraries A and B and leave Libraries C and D alone. Do I need to include a line in the merge table for Library C and Library D? Or can I omit them and they will just get run from the single R1/R2 fastqs? The example from github seems to show every file on its own line.

2) What is the order of operations for merge tables?

From the docs (about merge tables and expansion characters)
> Warning: do not use both of these options simultaneously for the same sample, it will lead to multiple merges.

If only a subset of samples is detailed in the merge table, does looper exclude these samples when trying to do the expansion character-based submissions? Are samples designated in merge tables NOT handled by expansion characters?

3) Here is my particular use case:

ACCx-B6E6F014-A599-4A58-A7A5-1F748471D662-X013-S12-L071-B1-T2-**P001**-GGACTCCT-ACGAATGT_S6_L007_R1_001.fastq.gz
ACCx-B6E6F014-A599-4A58-A7A5-1F748471D662-X013-S12-L071-B1-T2-**P001**-GGACTCCT-ACGAATGT_S6_L007_R2_001.fastq.gz

ACCx-B6E6F014-A599-4A58-A7A5-1F748471D662-X013-S12-L071-B1-T2-**P002**-CCGTTTGT-ATTGAACC_S4_L002_R1_001.fastq.gz
ACCx-B6E6F014-A599-4A58-A7A5-1F748471D662-X013-S12-L071-B1-T2-**P002**-CCGTTTGT-ATTGAACC_S4_L002_R2_001.fastq.gz

Desired merged sample name:
ACCx-B6E6F014-A599-4A58-A7A5-1F748471D662-X013-S12-L071-B1-T2-**PMRG**

How would I designate this with a merge table?

**Comment by nsheff** [comment]
I'll try to clarify the docs tomorrow. A few quick things:

> Or can I omit them and they will just get run from the single R1/R2 fastqs?

Yes, you can omit them. It will only merge the things in the merge table. (or you can include them as just 1 row in the merge table, it will do the same thing)

> If only a subset of samples is detailed in the merge table, does looper exclude these samples when trying to do the expansion character-based submissions? Are samples designated in merge tables NOT handled by expansion characters?

If you try to merge *and* use an asterisk...then I think it will first expand the asterisk, and then it will merge those expanded items. Maybe that's actually what you want...

> Here is my particular use case:

In this case, can't you just use an asterisk and no merge table? put `ACCx-B6E6F014-A599-4A58-A7A5-1F748471D662-X013-S12-L071-B1-T2-PMRG` under `sample_name`, and then put "source" under `read1` and "source2" under `read2` (or whatever), and specify the sources in your project_config like so: 
```
source1: "ACCx-B6E6F014-A599-4A58-A7A5-1F748471D662-X013-S12-L071-B1-T2-P*_R1_001.fastq.gz"
source2: "ACCx-B6E6F014-A599-4A58-A7A5-1F748471D662-X013-S12-L071-B1-T2-P*_R2_001.fastq.gz"
```

**Comment by nsheff** [comment]
> How would I designate this with a merge table?

If you do want to specify with a merge table, then you just leave `read1` and `read2` empty in the annotation table, and instead have this in your merge table:

sample_name | read1 | read2
------ | --------------- | ------------
ACCx-B6E6F014-A599-4A58-A7A5-1F748471D662-X013-S12-L071-B1-T2-PMRG | r1 | 4r2

**Comment by nsheff** [comment]
also just generally speaking, if I were you, I'd parse that complicated sample name out. have a column called "bio_rep" and store it as "2" instead of encoding that stuff in the sample_name. Make the sample name as short as it can be while still being unique.

**Comment by nsheff** [comment]
> Are samples designated in merge tables NOT handled by expansion characters? 

I think you're right; merged samples are NOT handled by expansion characters. Should this be changed? Can you think of a use case?

I've updated docs on merge tables (FYI: we're shortly going to change the name to `sample_subannotation`)

https://pepkit.github.io/docs/sample_subannotation/

I also added 2 new examples in this repository (examples 3 and 4) that demonstrate more complex merging, and mixing merges with wildcards:

https://github.com/pepkit/example_peps

Do these updates address your concerns?

**Comment by rcorces** [comment]
This was very helpful - thanks for taking the time to explain it. Theres a lot to parse through here. This can clearly get complicated fast.

> I think you're right; merged samples are NOT handled by expansion characters. Should this be changed? 

I think this is how it should be. Merged samples are explicitly merged and then not handled by expansion characters.

> Do these updates address your concerns?

Yes. The new docs are much more clear on merge tables. The pep kit website in general is really nice and flows well. A few comments below.

> If you do want to specify with a merge table, then you just leave read1 and read2 empty in the annotation table

This piece of info is not clear in the documents. The examples in the "example_peps" folder dont have multiple reads in the sample_annotation.csv either. I think this is the solution that I like the best though. 

> also just generally speaking, if I were you, I'd parse that complicated sample name out. have a column called "bio_rep" and store it as "2" instead of encoding that stuff in the sample_name. Make the sample name as short as it can be while still being unique.

This one confuses me. Am I correct in assuming that sample_name from the sample_annotation.csv file becomes the prefix for all of the downstream files and directories? If I want my directories to have that full name (with bio rep, tech rep, etc) then I need the sample name to include all of that as well right? I think this was the sticking point for me in figuring out the merge_table concept.

**Comment by nsheff** [comment]
> This piece of info is not clear in the documents. The examples in the "example_peps" folder dont have multiple reads in the sample_annotation.csv either. I think this is the solution that I like the best though.

Ok I've added example5 that does this. This is what I was trying to get at with this text: 

> - You *do not* need to include samples in the merge table if they do not need to be merged. Just include them in the primary annotation table. However, this means you'll need to make sure you provide the correct columns in the primary `sample_annotation` sheet; the simple example above assumes every sample is merged, so it doesn't need to define `file` in the `sample_annotation`. If you had unmerged samples, you'd need to specify that column.

I've tried to clarify the docs; added a paragraph and new example to the main page as well.

> Am I correct in assuming that sample_name from the sample_annotation.csv file becomes the prefix for all of the downstream files and directories? If I want my directories to have that full name (with bio rep, tech rep, etc) then I need the sample name to include all of that as well right? I think this was the sticking point for me in figuring out the merge_table concept.

Yes, you are correct. And yes, the sample name must match. 

I would just personally prefer to have shorter folder names. To me this stuff is not useful in a folder/sample name: "B6E6F014-A599-4A58-A7A5-1F748471D66"

**Comment by rcorces** [comment]
> I would just personally prefer to have shorter folder names. To me this stuff is not useful in a folder/sample name: "B6E6F014-A599-4A58-A7A5-1F748471D66"

That IS my sample name haha! That is the unique identifier name from the TCGA people. It is unfortunate.

This is all really great now. Thank you! Closing.
