### ISSUE TITLE
moving command arguments up one level for caravel

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#83]
`caravel` wants to run some looper processes. The naive way we are currently doing this just calls `looper cmd` on the command-line from `caravel`, like this:

## option 1
`caravel` -> `looper` -> run

It would be better if, instead, `caravel` could `import looper`, and then have direct access to the functions (like, for example, the `Runner` function object), and could run them directly in python without going through the `looper` CLI.

## option 2
`caravel` -> run
`looper` -> run

To do this, we have to:

1. move the cmd arguments into a universal language that can be processed either on the CLI (via `ArgumentParser`, as we do now), or via HTML. We could possibly use something like [argparseweb](https://github.com/nirizr/argparseweb) for this.

2. Make the `Runner.__call__ ` and other call functions accept arguments from a universal source, instead of only an `ArgumentParser` object.

This makes it so one code base could feed both the CLI and any other interface into looper commands.

**Comment by nsheff** [comment]
@vreuter do you have any thoughts on the best way to implement this?

**Comment by vreuter** [comment]
What about an `AttributeDict` (either one of our own implementations, or an external package) as the unifying object, since a `Namespace` essentially distills to a key-value mapping?

**Comment by nsheff** [comment]
yeah. or possibly just using an ArgumentParser could actually work.... we would just need a way to convert it into HTML.

**Comment by michalstolarczyk** [comment]
Could we modify `looper` to do something *like* this?

**`parser.py`**
```python
import argparse
import sys


def def_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument("-t", dest="test", default="tt", help="test argument")
    parser.add_argument("-p", dest="parser", action="store_true", help="get parser and exit")
    return parser


def main():
    parser = def_parser()
    args = parser.parse_args()
    if args.parser == True:
        # get parser and exit
        for action in parser._actions:
            # print parser for caravel
            print(action.dest)
            print(action.option_strings)
        sys.exit()
    # else: looper continues


if __name__ == "__main__":
    main()
```
It would need to return the parser instead of the output of `parser.parse_known_args()`

Then in **`caravel.py`** we could run a subprocess: `looper` with `-p` flag which would return just the parser:

```python
import shlex
import subprocess

p = subprocess.check_output(args=shlex.split("python parser.py -p"), shell=False)
# process output ...
args = p.split('\n')
print(args)
```

**Comment by nsheff** [comment]
I don't understand the logic there... you're saying call `looper -p` to get the return output as text? 

But why would you need to do that? We already have access to the actual `ArgumentParser` object in python...

**Comment by nsheff** [comment]
Yes, we should make `def_parser` return the parser.

But then we need not invoke `looper -p`, we should simply build the forms from the returned parser object.

**Comment by michalstolarczyk** [comment]
The `parse_arguments` function alters the results of `parse_known_args` (`args` and `remaining args`) before returning them:

https://github.com/pepkit/looper/blob/cb4bc15f1d175dbd1a4dea6897d8577b9f44eb5c/looper/looper.py#L191-L215

... so maybe `parse_arguments` could return the `parser` *along with* the current objects?
Then we could use it in `caravel` and simply discard later in `looper`. What do you think?

**Comment by vreuter** [comment]
@nsheff how would you like this to be implemented?

**Comment by nsheff** [comment]
@vreuter I don't have a preference, I'm open to ideas. I saw you working on one approach in #87 and made a comment there.

I like the class approach, it makes sense to me.

**Comment by nsheff** [comment]
From this https://github.com/pepkit/looper/pull/88#issuecomment-448451199, I wanted to capture this thought that I'm excited about here:

Is it possible to just get all the information we need from the actual ArgumentParser object itself? If we could do it that way, I think it would be really simple. In other words, create the ArgumentParser object in looper. Then import that into caravel and inspect it to get whatever we need.

I have no idea if you can get everything you need from that, but if you can, that would be pretty slick.

If it doesn't quite give us all the information we need, could we write a new class that extends ArgumentParser?  For example, in this new, SuperArgumentParser object, what if you, for example, override `add_argument` to do add whatever functionality we need, and then just call the base `self.add_argument` function right there with the same args?

We could use the `CliOpt` class @vreuter created in #89. and create those objects, append them to the ArgumentParser, with all the information we need.

Ideally, `SuperArgumentParser` (or whatever) would have exactly the same interface as `ArgumentParser`, but would record whatever else we need to make nice HTML output.

**Comment by nsheff** [comment]
@vreuter since you've been working on this and are more familiar with looper, do you want to take this one (remove assignment from @michalstolarczyk) and come up with the way you would solve this (feel free to ignore my suggestion if you have a better way).

we discussed yesterday and thought that would be fine, as @michalstolarczyk is starting to work on https://github.com/databio/caravel/issues/34

we can then use what you come up with here to implement the caravel 0.2 changes.

**Comment by michalstolarczyk** [comment]
> Is it possible to just get all the information we need from the actual ArgumentParser object itself? 

Yes, it is possible - this is what I was trying to do in the few commits in https://github.com/databio/caravel/tree/dev_0.2 few days ago. 

But I'm ok with doing it different way, which may be better.

**Comment by vreuter** [comment]
I'm happy to do it whatever way; I think it'll be really useful regardless. Soon it will also be even easier to brainstorm and exchange ideas.

**Comment by nsheff** [comment]
There hasn't been any discussion on this, is it because we've basically solved it just by moving forward?

**Comment by vreuter** [comment]
> There hasn't been any discussion on this, is it because we've basically solved it just by moving forward?

That seems right to me; I think that exposing the looper CLI parser builder, and the changes in `argparser_caravel` and `dev` changes in `looper` and in `caravel` itself collectively accomplish this, or at least move in that direction?

**Comment by nsheff** [comment]
OK @michalstolarczyk close this if it's satisfactory for you and caravel

**Comment by michalstolarczyk** [comment]
`caravel` says that he's satisfied. So am I.
