### ISSUE TITLE
globs and merges

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#9]
For samples in a project with a merge table, samples that are *not* merged should still allow wildcards for merges. 

This is not currently the case. See example4 in [`example_peps`](https://github.com/pepkit/example_peps)

**Comment by vreuter** [comment]
@nsheff do you know if this is still an issue? Also, it looks like the example peps may have been renamed?

**Comment by nsheff** [comment]
I believe this is still an issue.

The examples have been renamed, you are right.

@michalstolarczyk -- do you know what happened to example4? I actually cannot find a corresponding example with that content anymore in the new version, it's like that sample got eliminated.

**Comment by nsheff** [comment]
we can always pull example4 out of the history if need be, but do know why this example was eliminated?

**Comment by michalstolarczyk** [comment]
[example_subannotation3](https://github.com/pepkit/example_peps/tree/master/example_subannotation3) is the corresponding one

**Comment by stolarczyk** [comment]
fixed:

```python
In [13]: p = Project("example_peps/example_subtable3/project_config.yaml")                                                                                           
INFO 10:23:34 | peppy.project:project:1003 > Reading sample table: 'example_peps/example_subtable3/sample_table.csv' 
INFO 10:23:34 | peppy.project:project:1133 > Reading subannotations: example_peps/example_subtable3/subsample_table.csv 

In [14]: p.samples[0].file                                                                                                                                                                                
Out[14]: 
['../data/frog1a_data.txt',
 '../data/frog1b_data.txt',
 '../data/frog1c_data.txt']

In [15]: p.samples[1].file                                                                                                                                                                                
Out[15]: 
['../data/frog2_data.txt',
 '../data/frog2a_data.txt',
 '../data/frog2b_data.txt']
```
