### ISSUE TITLE
streamline argument parser for use in caravel

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#92]
As discussed in #83, it's nice if we can use the arguments from looper's argumentparser in caravel.

One thing that would make this easier to is to make sure we have `type` set correctly, and the help text updated. for example the `env` option isn't of type `file` (can it be?).  then we know to use a `Browse` box for that one.

Furthermore, we may need additional info in caravel, so we might want to subclass these `Action` classes to allow them to take additional parameters we would use in the HTML generation (unless it's possible to include extra parameters by default...). alternatively we can just store that informatino elsewhere as a list.

actually, even better, we can define our own `Type` objects that fill the argumentParser requirements (callable and return the converted value) but also implement any other methods we need for caravel.

**Comment by michalstolarczyk** [comment]
> actually, even better, we can define our own Type objects that fill the argumentParser requirements (callable and return the converted value) but also implement any other methods we need for caravel.

Yes, using existing `type` argument might be the best approach. It could be as easy as this:
```python
def new_type(arg):
    return {"value": arg,
            "our_data": "select"}

parser = argparse.ArgumentParser()
parser.add_argument('--foo', 'foo', type=new_type)
```
And then, after building the looper parser in caravel we can get the data out of the type:
```
parser._actions[-1].type("test")
```
```
Out[82]: {'our_data': 'select', 'value': 'test'}
```

**Comment by michalstolarczyk** [comment]
This is already resolved in `argparser_caravel` https://github.com/pepkit/looper/blob/argparser_caravel/looper/parser_types.py
