### ISSUE TITLE
Run related actions not in Runner __call__

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/looper#95]
raised in discussion with @nsheff a few days ago

Would it be possible to include the following lines in the `Runner.__call__`? 

https://github.com/pepkit/looper/blob/0d2db9d57acf087e8ae9cf066d0e7d7f6dbf050b/looper/looper.py#L846-L864

This steps are executed *only* in case the `run` command is called anyway. 

We need to use `Runner()` in [caravel](https://github.com/pepkit/caravel). Using current implementation would mean that and this steps would need to be reproduced and maintained in two places.

**Comment by vreuter** [comment]
OK, if you now pull `argparser_caravel` you should get the updates.
